/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BlockEvidence model module.
 * @module model/BlockEvidence
 * @version 3.0
 */
class BlockEvidence {
    /**
     * Constructs a new <code>BlockEvidence</code>.
     * @alias module:model/BlockEvidence
     */
    constructor() { 
        
        BlockEvidence.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BlockEvidence</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockEvidence} obj Optional instance to populate.
     * @return {module:model/BlockEvidence} The populated <code>BlockEvidence</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockEvidence();

            if (data.hasOwnProperty('evidence')) {
                obj['evidence'] = ApiClient.convertToType(data['evidence'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} evidence
 */
BlockEvidence.prototype['evidence'] = undefined;






export default BlockEvidence;

