/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlockIDParts from './BlockIDParts';

/**
 * The BlockID model module.
 * @module model/BlockID
 * @version 3.0
 */
class BlockID {
    /**
     * Constructs a new <code>BlockID</code>.
     * @alias module:model/BlockID
     * @param hash {String} 
     * @param parts {module:model/BlockIDParts} 
     */
    constructor(hash, parts) { 
        
        BlockID.initialize(this, hash, parts);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, hash, parts) { 
        obj['hash'] = hash;
        obj['parts'] = parts;
    }

    /**
     * Constructs a <code>BlockID</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockID} obj Optional instance to populate.
     * @return {module:model/BlockID} The populated <code>BlockID</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockID();

            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
            if (data.hasOwnProperty('parts')) {
                obj['parts'] = BlockIDParts.constructFromObject(data['parts']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} hash
 */
BlockID.prototype['hash'] = undefined;

/**
 * @member {module:model/BlockIDParts} parts
 */
BlockID.prototype['parts'] = undefined;






export default BlockID;

