/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlockID from './BlockID';
import BlockLastCommitPrecommits from './BlockLastCommitPrecommits';

/**
 * The BlockLastCommit model module.
 * @module model/BlockLastCommit
 * @version 3.0
 */
class BlockLastCommit {
    /**
     * Constructs a new <code>BlockLastCommit</code>.
     * @alias module:model/BlockLastCommit
     */
    constructor() { 
        
        BlockLastCommit.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BlockLastCommit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockLastCommit} obj Optional instance to populate.
     * @return {module:model/BlockLastCommit} The populated <code>BlockLastCommit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockLastCommit();

            if (data.hasOwnProperty('block_id')) {
                obj['block_id'] = BlockID.constructFromObject(data['block_id']);
            }
            if (data.hasOwnProperty('precommits')) {
                obj['precommits'] = ApiClient.convertToType(data['precommits'], [BlockLastCommitPrecommits]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BlockID} block_id
 */
BlockLastCommit.prototype['block_id'] = undefined;

/**
 * @member {Array.<module:model/BlockLastCommitPrecommits>} precommits
 */
BlockLastCommit.prototype['precommits'] = undefined;






export default BlockLastCommit;

