/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Hash from './Hash';

/**
* The BlockID model module.
* @module model/BlockID
* @version 3.0
*/
export default class BlockID {
    /**
    * Constructs a new <code>BlockID</code>.
    * @alias module:model/BlockID
    * @class
    * @param hash {module:model/Hash} 
    * @param parts {Object} 
    */

    constructor(hash, parts) {
        
        
        this['hash'] = hash;
        this['parts'] = parts;
        
    }

    /**
    * Constructs a <code>BlockID</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BlockID} obj Optional instance to populate.
    * @return {module:model/BlockID} The populated <code>BlockID</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockID();
                        
            
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = Hash.constructFromObject(data['hash']);
            }
            if (data.hasOwnProperty('parts')) {
                obj['parts'] = ApiClient.convertToType(data['parts'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Hash} hash
    */
    hash = undefined;
    /**
    * @member {Object} parts
    */
    parts = undefined;




}
