/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlockHeader from './BlockHeader';

/**
* The Block model module.
* @module model/Block
* @version 3.0
*/
export default class Block {
    /**
    * Constructs a new <code>Block</code>.
    * @alias module:model/Block
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Block</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Block} obj Optional instance to populate.
    * @return {module:model/Block} The populated <code>Block</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Block();
                        
            
            if (data.hasOwnProperty('header')) {
                obj['header'] = BlockHeader.constructFromObject(data['header']);
            }
            if (data.hasOwnProperty('txs')) {
                obj['txs'] = ApiClient.convertToType(data['txs'], ['String']);
            }
            if (data.hasOwnProperty('evidence')) {
                obj['evidence'] = ApiClient.convertToType(data['evidence'], Object);
            }
            if (data.hasOwnProperty('last_commit')) {
                obj['last_commit'] = ApiClient.convertToType(data['last_commit'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/BlockHeader} header
    */
    header = undefined;
    /**
    * @member {Array.<String>} txs
    */
    txs = undefined;
    /**
    * @member {Object} evidence
    */
    evidence = undefined;
    /**
    * @member {Object} last_commit
    */
    last_commit = undefined;




}
