/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Block from './Block';
import BlockQueryBlockMeta from './BlockQueryBlockMeta';

/**
 * The BlockQuery model module.
 * @module model/BlockQuery
 * @version 3.0
 */
class BlockQuery {
    /**
     * Constructs a new <code>BlockQuery</code>.
     * @alias module:model/BlockQuery
     */
    constructor() { 
        
        BlockQuery.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BlockQuery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockQuery} obj Optional instance to populate.
     * @return {module:model/BlockQuery} The populated <code>BlockQuery</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockQuery();

            if (data.hasOwnProperty('block_meta')) {
                obj['block_meta'] = BlockQueryBlockMeta.constructFromObject(data['block_meta']);
            }
            if (data.hasOwnProperty('block')) {
                obj['block'] = Block.constructFromObject(data['block']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BlockQueryBlockMeta} block_meta
 */
BlockQuery.prototype['block_meta'] = undefined;

/**
 * @member {module:model/Block} block
 */
BlockQuery.prototype['block'] = undefined;






export default BlockQuery;

