/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateOrderInfo model module.
 * @module model/CreateOrderInfo
 * @version 3.0
 */
class CreateOrderInfo {
    /**
     * Constructs a new <code>CreateOrderInfo</code>.
     * @alias module:model/CreateOrderInfo
     */
    constructor() { 
        
        CreateOrderInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateOrderInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateOrderInfo} obj Optional instance to populate.
     * @return {module:model/CreateOrderInfo} The populated <code>CreateOrderInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateOrderInfo();

            if (data.hasOwnProperty('order_id')) {
                obj['order_id'] = ApiClient.convertToType(data['order_id'], 'String');
            }
            if (data.hasOwnProperty('sender')) {
                obj['sender'] = ApiClient.convertToType(data['sender'], 'String');
            }
            if (data.hasOwnProperty('trading_pair')) {
                obj['trading_pair'] = ApiClient.convertToType(data['trading_pair'], 'String');
            }
            if (data.hasOwnProperty('order_type')) {
                obj['order_type'] = ApiClient.convertToType(data['order_type'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('side')) {
                obj['side'] = ApiClient.convertToType(data['side'], 'Number');
            }
            if (data.hasOwnProperty('time_in_force')) {
                obj['time_in_force'] = ApiClient.convertToType(data['time_in_force'], 'Number');
            }
            if (data.hasOwnProperty('feature_fee')) {
                obj['feature_fee'] = ApiClient.convertToType(data['feature_fee'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('frozen_fee')) {
                obj['frozen_fee'] = ApiClient.convertToType(data['frozen_fee'], 'Number');
            }
            if (data.hasOwnProperty('freeze')) {
                obj['freeze'] = ApiClient.convertToType(data['freeze'], 'Number');
            }
            if (data.hasOwnProperty('tx_hash')) {
                obj['tx_hash'] = ApiClient.convertToType(data['tx_hash'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} order_id
 */
CreateOrderInfo.prototype['order_id'] = undefined;

/**
 * bech32 encoded address
 * @member {String} sender
 */
CreateOrderInfo.prototype['sender'] = undefined;

/**
 * @member {String} trading_pair
 */
CreateOrderInfo.prototype['trading_pair'] = undefined;

/**
 * Limited value 2
 * @member {Number} order_type
 */
CreateOrderInfo.prototype['order_type'] = undefined;

/**
 * @member {String} price
 */
CreateOrderInfo.prototype['price'] = undefined;

/**
 * @member {Number} quantity
 */
CreateOrderInfo.prototype['quantity'] = undefined;

/**
 * BUY:1/SELL:2
 * @member {Number} side
 */
CreateOrderInfo.prototype['side'] = undefined;

/**
 * GTE:3/IOC:4
 * @member {Number} time_in_force
 */
CreateOrderInfo.prototype['time_in_force'] = undefined;

/**
 * Order feature fee, sato.CET as the unit
 * @member {Number} feature_fee
 */
CreateOrderInfo.prototype['feature_fee'] = undefined;

/**
 * @member {Number} height
 */
CreateOrderInfo.prototype['height'] = undefined;

/**
 * Order frozen fee, sato.CET as the unit
 * @member {Number} frozen_fee
 */
CreateOrderInfo.prototype['frozen_fee'] = undefined;

/**
 * Freeze sato.CET amount
 * @member {Number} freeze
 */
CreateOrderInfo.prototype['freeze'] = undefined;

/**
 * The tx hash
 * @member {String} tx_hash
 */
CreateOrderInfo.prototype['tx_hash'] = undefined;






export default CreateOrderInfo;

