/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import KVPair from './KVPair';

/**
* The DeliverTxResult model module.
* @module model/DeliverTxResult
* @version 3.0
*/
export default class DeliverTxResult {
    /**
    * Constructs a new <code>DeliverTxResult</code>.
    * @alias module:model/DeliverTxResult
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>DeliverTxResult</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DeliverTxResult} obj Optional instance to populate.
    * @return {module:model/DeliverTxResult} The populated <code>DeliverTxResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeliverTxResult();
                        
            
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
            if (data.hasOwnProperty('gas_used')) {
                obj['gas_used'] = ApiClient.convertToType(data['gas_used'], 'Number');
            }
            if (data.hasOwnProperty('gas_wanted')) {
                obj['gas_wanted'] = ApiClient.convertToType(data['gas_wanted'], 'Number');
            }
            if (data.hasOwnProperty('info')) {
                obj['info'] = ApiClient.convertToType(data['info'], 'String');
            }
            if (data.hasOwnProperty('log')) {
                obj['log'] = ApiClient.convertToType(data['log'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [KVPair]);
            }
        }
        return obj;
    }

    /**
    * @member {Number} code
    */
    code = undefined;
    /**
    * @member {String} data
    */
    data = undefined;
    /**
    * @member {Number} gas_used
    */
    gas_used = undefined;
    /**
    * @member {Number} gas_wanted
    */
    gas_wanted = undefined;
    /**
    * @member {String} info
    */
    info = undefined;
    /**
    * @member {String} log
    */
    log = undefined;
    /**
    * @member {Array.<module:model/KVPair>} tags
    */
    tags = undefined;




}
