/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import KVPair from './KVPair';

/**
 * The DeliverTxResult model module.
 * @module model/DeliverTxResult
 * @version 3.0
 */
class DeliverTxResult {
    /**
     * Constructs a new <code>DeliverTxResult</code>.
     * @alias module:model/DeliverTxResult
     */
    constructor() { 
        
        DeliverTxResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeliverTxResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeliverTxResult} obj Optional instance to populate.
     * @return {module:model/DeliverTxResult} The populated <code>DeliverTxResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeliverTxResult();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
            if (data.hasOwnProperty('gas_used')) {
                obj['gas_used'] = ApiClient.convertToType(data['gas_used'], 'Number');
            }
            if (data.hasOwnProperty('gas_wanted')) {
                obj['gas_wanted'] = ApiClient.convertToType(data['gas_wanted'], 'Number');
            }
            if (data.hasOwnProperty('info')) {
                obj['info'] = ApiClient.convertToType(data['info'], 'String');
            }
            if (data.hasOwnProperty('log')) {
                obj['log'] = ApiClient.convertToType(data['log'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [KVPair]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} code
 */
DeliverTxResult.prototype['code'] = undefined;

/**
 * @member {String} data
 */
DeliverTxResult.prototype['data'] = undefined;

/**
 * @member {Number} gas_used
 */
DeliverTxResult.prototype['gas_used'] = undefined;

/**
 * @member {Number} gas_wanted
 */
DeliverTxResult.prototype['gas_wanted'] = undefined;

/**
 * @member {String} info
 */
DeliverTxResult.prototype['info'] = undefined;

/**
 * @member {String} log
 */
DeliverTxResult.prototype['log'] = undefined;

/**
 * @member {Array.<module:model/KVPair>} tags
 */
DeliverTxResult.prototype['tags'] = undefined;






export default DeliverTxResult;

