/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FillOrderInfo model module.
 * @module model/FillOrderInfo
 * @version 3.0
 */
class FillOrderInfo {
    /**
     * Constructs a new <code>FillOrderInfo</code>.
     * @alias module:model/FillOrderInfo
     */
    constructor() { 
        
        FillOrderInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FillOrderInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FillOrderInfo} obj Optional instance to populate.
     * @return {module:model/FillOrderInfo} The populated <code>FillOrderInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FillOrderInfo();

            if (data.hasOwnProperty('order_id')) {
                obj['order_id'] = ApiClient.convertToType(data['order_id'], 'String');
            }
            if (data.hasOwnProperty('trading_pair')) {
                obj['trading_pair'] = ApiClient.convertToType(data['trading_pair'], 'String');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('side')) {
                obj['side'] = ApiClient.convertToType(data['side'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'String');
            }
            if (data.hasOwnProperty('left_stock')) {
                obj['left_stock'] = ApiClient.convertToType(data['left_stock'], 'Number');
            }
            if (data.hasOwnProperty('freeze')) {
                obj['freeze'] = ApiClient.convertToType(data['freeze'], 'Number');
            }
            if (data.hasOwnProperty('deal_stock')) {
                obj['deal_stock'] = ApiClient.convertToType(data['deal_stock'], 'Number');
            }
            if (data.hasOwnProperty('deal_money')) {
                obj['deal_money'] = ApiClient.convertToType(data['deal_money'], 'Number');
            }
            if (data.hasOwnProperty('curr_stock')) {
                obj['curr_stock'] = ApiClient.convertToType(data['curr_stock'], 'Number');
            }
            if (data.hasOwnProperty('curr_money')) {
                obj['curr_money'] = ApiClient.convertToType(data['curr_money'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} order_id
 */
FillOrderInfo.prototype['order_id'] = undefined;

/**
 * @member {String} trading_pair
 */
FillOrderInfo.prototype['trading_pair'] = undefined;

/**
 * @member {Number} height
 */
FillOrderInfo.prototype['height'] = undefined;

/**
 * BUY:1/SELL:2
 * @member {Number} side
 */
FillOrderInfo.prototype['side'] = undefined;

/**
 * @member {String} price
 */
FillOrderInfo.prototype['price'] = undefined;

/**
 * Order left stock
 * @member {Number} left_stock
 */
FillOrderInfo.prototype['left_stock'] = undefined;

/**
 * Freeze sato.CET amount
 * @member {Number} freeze
 */
FillOrderInfo.prototype['freeze'] = undefined;

/**
 * Order accumulated deal stock amount
 * @member {Number} deal_stock
 */
FillOrderInfo.prototype['deal_stock'] = undefined;

/**
 * Order accumulated deal money amount
 * @member {Number} deal_money
 */
FillOrderInfo.prototype['deal_money'] = undefined;

/**
 * Current block deal stock amount
 * @member {Number} curr_stock
 */
FillOrderInfo.prototype['curr_stock'] = undefined;

/**
 * Current block deal money amount
 * @member {Number} curr_money
 */
FillOrderInfo.prototype['curr_money'] = undefined;






export default FillOrderInfo;

