/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Hash model module.
* @module model/Hash
* @version 3.0
*/
export default class Hash {
    /**
    * Constructs a new <code>Hash</code>.
    * @alias module:model/Hash
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Hash</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Hash} obj Optional instance to populate.
    * @return {module:model/Hash} The populated <code>Hash</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Hash();
                        
            
        }
        return obj;
    }





}
