/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseReq from './BaseReq';

/**
 * The InlineObject28 model module.
 * @module model/InlineObject28
 * @version 3.0
 */
class InlineObject28 {
    /**
     * Constructs a new <code>InlineObject28</code>.
     * @alias module:model/InlineObject28
     * @param baseReq {module:model/BaseReq} 
     * @param tradingPair {String} 
     * @param time {String} 
     */
    constructor(baseReq, tradingPair, time) { 
        
        InlineObject28.initialize(this, baseReq, tradingPair, time);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, baseReq, tradingPair, time) { 
        obj['base_req'] = baseReq;
        obj['trading_pair'] = tradingPair;
        obj['time'] = time;
    }

    /**
     * Constructs a <code>InlineObject28</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject28} obj Optional instance to populate.
     * @return {module:model/InlineObject28} The populated <code>InlineObject28</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject28();

            if (data.hasOwnProperty('base_req')) {
                obj['base_req'] = BaseReq.constructFromObject(data['base_req']);
            }
            if (data.hasOwnProperty('trading_pair')) {
                obj['trading_pair'] = ApiClient.convertToType(data['trading_pair'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BaseReq} base_req
 */
InlineObject28.prototype['base_req'] = undefined;

/**
 * @member {String} trading_pair
 */
InlineObject28.prototype['trading_pair'] = undefined;

/**
 * @member {String} time
 */
InlineObject28.prototype['time'] = undefined;






export default InlineObject28;

