/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse200ApplicationVersion model module.
 * @module model/InlineResponse200ApplicationVersion
 * @version 3.0
 */
class InlineResponse200ApplicationVersion {
    /**
     * Constructs a new <code>InlineResponse200ApplicationVersion</code>.
     * @alias module:model/InlineResponse200ApplicationVersion
     */
    constructor() { 
        
        InlineResponse200ApplicationVersion.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse200ApplicationVersion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse200ApplicationVersion} obj Optional instance to populate.
     * @return {module:model/InlineResponse200ApplicationVersion} The populated <code>InlineResponse200ApplicationVersion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200ApplicationVersion();

            if (data.hasOwnProperty('build_tags')) {
                obj['build_tags'] = ApiClient.convertToType(data['build_tags'], 'String');
            }
            if (data.hasOwnProperty('client_name')) {
                obj['client_name'] = ApiClient.convertToType(data['client_name'], 'String');
            }
            if (data.hasOwnProperty('commit')) {
                obj['commit'] = ApiClient.convertToType(data['commit'], 'String');
            }
            if (data.hasOwnProperty('go')) {
                obj['go'] = ApiClient.convertToType(data['go'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('server_name')) {
                obj['server_name'] = ApiClient.convertToType(data['server_name'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} build_tags
 */
InlineResponse200ApplicationVersion.prototype['build_tags'] = undefined;

/**
 * @member {String} client_name
 */
InlineResponse200ApplicationVersion.prototype['client_name'] = undefined;

/**
 * @member {String} commit
 */
InlineResponse200ApplicationVersion.prototype['commit'] = undefined;

/**
 * @member {String} go
 */
InlineResponse200ApplicationVersion.prototype['go'] = undefined;

/**
 * @member {String} name
 */
InlineResponse200ApplicationVersion.prototype['name'] = undefined;

/**
 * @member {String} server_name
 */
InlineResponse200ApplicationVersion.prototype['server_name'] = undefined;

/**
 * @member {String} version
 */
InlineResponse200ApplicationVersion.prototype['version'] = undefined;






export default InlineResponse200ApplicationVersion;

