/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse20049 model module.
 * @module model/InlineResponse20049
 * @version 3.0
 */
class InlineResponse20049 {
    /**
     * Constructs a new <code>InlineResponse20049</code>.
     * @alias module:model/InlineResponse20049
     */
    constructor() { 
        
        InlineResponse20049.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20049</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20049} obj Optional instance to populate.
     * @return {module:model/InlineResponse20049} The populated <code>InlineResponse20049</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20049();

            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'String');
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} height
 */
InlineResponse20049.prototype['height'] = undefined;

/**
 * @member {Array.<String>} result
 */
InlineResponse20049.prototype['result'] = undefined;






export default InlineResponse20049;

