/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseReq from './BaseReq';
import Coin from './Coin';

/**
 * The InlineObject6 model module.
 * @module model/InlineObject6
 * @version 3.0
 */
class InlineObject6 {
    /**
     * Constructs a new <code>InlineObject6</code>.
     * @alias module:model/InlineObject6
     */
    constructor() { 
        
        InlineObject6.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject6</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject6} obj Optional instance to populate.
     * @return {module:model/InlineObject6} The populated <code>InlineObject6</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject6();

            if (data.hasOwnProperty('base_req')) {
                obj['base_req'] = BaseReq.constructFromObject(data['base_req']);
            }
            if (data.hasOwnProperty('delegator_address')) {
                obj['delegator_address'] = ApiClient.convertToType(data['delegator_address'], 'String');
            }
            if (data.hasOwnProperty('validator_address')) {
                obj['validator_address'] = ApiClient.convertToType(data['validator_address'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = Coin.constructFromObject(data['amount']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BaseReq} base_req
 */
InlineObject6.prototype['base_req'] = undefined;

/**
 * bech32 encoded address
 * @member {String} delegator_address
 */
InlineObject6.prototype['delegator_address'] = undefined;

/**
 * bech32 encoded address
 * @member {String} validator_address
 */
InlineObject6.prototype['validator_address'] = undefined;

/**
 * @member {module:model/Coin} amount
 */
InlineObject6.prototype['amount'] = undefined;






export default InlineObject6;

