/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse20013Result model module.
 * @module model/InlineResponse20013Result
 * @version 3.0
 */
class InlineResponse20013Result {
    /**
     * Constructs a new <code>InlineResponse20013Result</code>.
     * @alias module:model/InlineResponse20013Result
     * @param notBondedTokens {String} 
     * @param bondedTokens {String} 
     * @param nonBondableTokens {String} 
     * @param totalSupply {String} 
     * @param bondedRatio {String} 
     */
    constructor(notBondedTokens, bondedTokens, nonBondableTokens, totalSupply, bondedRatio) { 
        
        InlineResponse20013Result.initialize(this, notBondedTokens, bondedTokens, nonBondableTokens, totalSupply, bondedRatio);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, notBondedTokens, bondedTokens, nonBondableTokens, totalSupply, bondedRatio) { 
        obj['not_bonded_tokens'] = notBondedTokens;
        obj['bonded_tokens'] = bondedTokens;
        obj['non_bondable_tokens'] = nonBondableTokens;
        obj['total_supply'] = totalSupply;
        obj['bonded_ratio'] = bondedRatio;
    }

    /**
     * Constructs a <code>InlineResponse20013Result</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20013Result} obj Optional instance to populate.
     * @return {module:model/InlineResponse20013Result} The populated <code>InlineResponse20013Result</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20013Result();

            if (data.hasOwnProperty('not_bonded_tokens')) {
                obj['not_bonded_tokens'] = ApiClient.convertToType(data['not_bonded_tokens'], 'String');
            }
            if (data.hasOwnProperty('bonded_tokens')) {
                obj['bonded_tokens'] = ApiClient.convertToType(data['bonded_tokens'], 'String');
            }
            if (data.hasOwnProperty('non_bondable_tokens')) {
                obj['non_bondable_tokens'] = ApiClient.convertToType(data['non_bondable_tokens'], 'String');
            }
            if (data.hasOwnProperty('total_supply')) {
                obj['total_supply'] = ApiClient.convertToType(data['total_supply'], 'String');
            }
            if (data.hasOwnProperty('bonded_ratio')) {
                obj['bonded_ratio'] = ApiClient.convertToType(data['bonded_ratio'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} not_bonded_tokens
 */
InlineResponse20013Result.prototype['not_bonded_tokens'] = undefined;

/**
 * @member {String} bonded_tokens
 */
InlineResponse20013Result.prototype['bonded_tokens'] = undefined;

/**
 * @member {String} non_bondable_tokens
 */
InlineResponse20013Result.prototype['non_bondable_tokens'] = undefined;

/**
 * @member {String} total_supply
 */
InlineResponse20013Result.prototype['total_supply'] = undefined;

/**
 * @member {String} bonded_ratio
 */
InlineResponse20013Result.prototype['bonded_ratio'] = undefined;






export default InlineResponse20013Result;

