/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PricePoint from './PricePoint';

/**
 * The InlineResponse20055 model module.
 * @module model/InlineResponse20055
 * @version 3.0
 */
class InlineResponse20055 {
    /**
     * Constructs a new <code>InlineResponse20055</code>.
     * @alias module:model/InlineResponse20055
     */
    constructor() { 
        
        InlineResponse20055.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20055</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20055} obj Optional instance to populate.
     * @return {module:model/InlineResponse20055} The populated <code>InlineResponse20055</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20055();

            if (data.hasOwnProperty('asks')) {
                obj['asks'] = ApiClient.convertToType(data['asks'], [PricePoint]);
            }
            if (data.hasOwnProperty('bids')) {
                obj['bids'] = ApiClient.convertToType(data['bids'], [PricePoint]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/PricePoint>} asks
 */
InlineResponse20055.prototype['asks'] = undefined;

/**
 * @member {Array.<module:model/PricePoint>} bids
 */
InlineResponse20055.prototype['bids'] = undefined;






export default InlineResponse20055;

