/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseReq from './BaseReq';
import Coin from './Coin';

/**
 * The InlineObject10 model module.
 * @module model/InlineObject10
 * @version 3.0
 */
class InlineObject10 {
    /**
     * Constructs a new <code>InlineObject10</code>.
     * @alias module:model/InlineObject10
     * @param baseReq {module:model/BaseReq} 
     * @param title {String} 
     * @param description {String} 
     * @param proposalType {String} 
     * @param proposer {String} bech32 encoded address
     * @param initialDeposit {Array.<module:model/Coin>} 
     */
    constructor(baseReq, title, description, proposalType, proposer, initialDeposit) { 
        
        InlineObject10.initialize(this, baseReq, title, description, proposalType, proposer, initialDeposit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, baseReq, title, description, proposalType, proposer, initialDeposit) { 
        obj['base_req'] = baseReq;
        obj['title'] = title;
        obj['description'] = description;
        obj['proposal_type'] = proposalType;
        obj['proposer'] = proposer;
        obj['initial_deposit'] = initialDeposit;
    }

    /**
     * Constructs a <code>InlineObject10</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject10} obj Optional instance to populate.
     * @return {module:model/InlineObject10} The populated <code>InlineObject10</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject10();

            if (data.hasOwnProperty('base_req')) {
                obj['base_req'] = BaseReq.constructFromObject(data['base_req']);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('proposal_type')) {
                obj['proposal_type'] = ApiClient.convertToType(data['proposal_type'], 'String');
            }
            if (data.hasOwnProperty('proposer')) {
                obj['proposer'] = ApiClient.convertToType(data['proposer'], 'String');
            }
            if (data.hasOwnProperty('initial_deposit')) {
                obj['initial_deposit'] = ApiClient.convertToType(data['initial_deposit'], [Coin]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BaseReq} base_req
 */
InlineObject10.prototype['base_req'] = undefined;

/**
 * @member {String} title
 */
InlineObject10.prototype['title'] = undefined;

/**
 * @member {String} description
 */
InlineObject10.prototype['description'] = undefined;

/**
 * @member {String} proposal_type
 */
InlineObject10.prototype['proposal_type'] = undefined;

/**
 * bech32 encoded address
 * @member {String} proposer
 */
InlineObject10.prototype['proposer'] = undefined;

/**
 * @member {Array.<module:model/Coin>} initial_deposit
 */
InlineObject10.prototype['initial_deposit'] = undefined;






export default InlineObject10;

