/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse20035Result model module.
 * @module model/InlineResponse20035Result
 * @version 3.0
 */
class InlineResponse20035Result {
    /**
     * Constructs a new <code>InlineResponse20035Result</code>.
     * @alias module:model/InlineResponse20035Result
     */
    constructor() { 
        
        InlineResponse20035Result.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20035Result</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20035Result} obj Optional instance to populate.
     * @return {module:model/InlineResponse20035Result} The populated <code>InlineResponse20035Result</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20035Result();

            if (data.hasOwnProperty('activation_fee')) {
                obj['activation_fee'] = ApiClient.convertToType(data['activation_fee'], 'String');
            }
            if (data.hasOwnProperty('lock_coins_fee')) {
                obj['lock_coins_fee'] = ApiClient.convertToType(data['lock_coins_fee'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} activation_fee
 */
InlineResponse20035Result.prototype['activation_fee'] = undefined;

/**
 * @member {String} lock_coins_fee
 */
InlineResponse20035Result.prototype['lock_coins_fee'] = undefined;






export default InlineResponse20035Result;

