/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseReq from './BaseReq';
import Coin from './Coin';

/**
 * The InlineObject8 model module.
 * @module model/InlineObject8
 * @version 3.0
 */
class InlineObject8 {
    /**
     * Constructs a new <code>InlineObject8</code>.
     * @alias module:model/InlineObject8
     * @param baseReq {module:model/BaseReq} 
     * @param delegatorAddress {String} bech32 encoded address
     * @param validatorSrcAddress {String} bech32 encoded address
     * @param validatorDstAddress {String} bech32 encoded address
     * @param amount {module:model/Coin} 
     */
    constructor(baseReq, delegatorAddress, validatorSrcAddress, validatorDstAddress, amount) { 
        
        InlineObject8.initialize(this, baseReq, delegatorAddress, validatorSrcAddress, validatorDstAddress, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, baseReq, delegatorAddress, validatorSrcAddress, validatorDstAddress, amount) { 
        obj['base_req'] = baseReq;
        obj['delegator_address'] = delegatorAddress;
        obj['validator_src_address'] = validatorSrcAddress;
        obj['validator_dst_address'] = validatorDstAddress;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>InlineObject8</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject8} obj Optional instance to populate.
     * @return {module:model/InlineObject8} The populated <code>InlineObject8</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject8();

            if (data.hasOwnProperty('base_req')) {
                obj['base_req'] = BaseReq.constructFromObject(data['base_req']);
            }
            if (data.hasOwnProperty('delegator_address')) {
                obj['delegator_address'] = ApiClient.convertToType(data['delegator_address'], 'String');
            }
            if (data.hasOwnProperty('validator_src_address')) {
                obj['validator_src_address'] = ApiClient.convertToType(data['validator_src_address'], 'String');
            }
            if (data.hasOwnProperty('validator_dst_address')) {
                obj['validator_dst_address'] = ApiClient.convertToType(data['validator_dst_address'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = Coin.constructFromObject(data['amount']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BaseReq} base_req
 */
InlineObject8.prototype['base_req'] = undefined;

/**
 * bech32 encoded address
 * @member {String} delegator_address
 */
InlineObject8.prototype['delegator_address'] = undefined;

/**
 * bech32 encoded address
 * @member {String} validator_src_address
 */
InlineObject8.prototype['validator_src_address'] = undefined;

/**
 * bech32 encoded address
 * @member {String} validator_dst_address
 */
InlineObject8.prototype['validator_dst_address'] = undefined;

/**
 * @member {module:model/Coin} amount
 */
InlineObject8.prototype['amount'] = undefined;






export default InlineObject8;

