/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse20036ResultPlans from './InlineResponse20036ResultPlans';

/**
 * The InlineResponse20036Result model module.
 * @module model/InlineResponse20036Result
 * @version 3.0
 */
class InlineResponse20036Result {
    /**
     * Constructs a new <code>InlineResponse20036Result</code>.
     * @alias module:model/InlineResponse20036Result
     */
    constructor() { 
        
        InlineResponse20036Result.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20036Result</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20036Result} obj Optional instance to populate.
     * @return {module:model/InlineResponse20036Result} The populated <code>InlineResponse20036Result</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20036Result();

            if (data.hasOwnProperty('default_reward_per_block')) {
                obj['default_reward_per_block'] = ApiClient.convertToType(data['default_reward_per_block'], 'String');
            }
            if (data.hasOwnProperty('plans')) {
                obj['plans'] = ApiClient.convertToType(data['plans'], [InlineResponse20036ResultPlans]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} default_reward_per_block
 */
InlineResponse20036Result.prototype['default_reward_per_block'] = undefined;

/**
 * @member {Array.<module:model/InlineResponse20036ResultPlans>} plans
 */
InlineResponse20036Result.prototype['plans'] = undefined;






export default InlineResponse20036Result;

