/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MarketInfoAllOf model module.
 * @module model/MarketInfoAllOf
 * @version 3.0
 */
class MarketInfoAllOf {
    /**
     * Constructs a new <code>MarketInfoAllOf</code>.
     * @alias module:model/MarketInfoAllOf
     */
    constructor() { 
        
        MarketInfoAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MarketInfoAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MarketInfoAllOf} obj Optional instance to populate.
     * @return {module:model/MarketInfoAllOf} The populated <code>MarketInfoAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MarketInfoAllOf();

            if (data.hasOwnProperty('last_executed_price')) {
                obj['last_executed_price'] = ApiClient.convertToType(data['last_executed_price'], 'String');
            }
            if (data.hasOwnProperty('creator')) {
                obj['creator'] = ApiClient.convertToType(data['creator'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} last_executed_price
 */
MarketInfoAllOf.prototype['last_executed_price'] = undefined;

/**
 * @member {String} creator
 */
MarketInfoAllOf.prototype['creator'] = undefined;






export default MarketInfoAllOf;

