/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseMarket from './BaseMarket';

/**
* The MarketInfo model module.
* @module model/MarketInfo
* @version 3.0
*/
export default class MarketInfo {
    /**
    * Constructs a new <code>MarketInfo</code>.
    * @alias module:model/MarketInfo
    * @class
    * @extends module:model/BaseMarket
    * @param stock {} 
    * @param money {} 
    * @param pricePrecision {} The trading-pair price precision, used to control the price accuracy of the order when token trades, valid range [0, 18]
    */

    constructor(stock, money, pricePrecision) {
        BaseMarket.call(this, stock, money, pricePrecision);
        
        
    }

    /**
    * Constructs a <code>MarketInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MarketInfo} obj Optional instance to populate.
    * @return {module:model/MarketInfo} The populated <code>MarketInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MarketInfo();
            
            BaseMarket.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('last_executed_price')) {
                obj['last_executed_price'] = ApiClient.convertToType(data['last_executed_price'], 'String');
            }
            if (data.hasOwnProperty('creator')) {
                obj['creator'] = ApiClient.convertToType(data['creator'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} last_executed_price
    */
    last_executed_price = undefined;
    /**
    * @member {String} creator
    */
    creator = undefined;




}
