/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TxQuery from './TxQuery';

/**
 * The PaginatedQueryTxs model module.
 * @module model/PaginatedQueryTxs
 * @version 3.0
 */
class PaginatedQueryTxs {
    /**
     * Constructs a new <code>PaginatedQueryTxs</code>.
     * @alias module:model/PaginatedQueryTxs
     * @param totalCount {Number} 
     * @param count {Number} 
     * @param pageNumber {Number} 
     * @param pageTotal {Number} 
     * @param limit {Number} 
     * @param txs {Array.<module:model/TxQuery>} 
     */
    constructor(totalCount, count, pageNumber, pageTotal, limit, txs) { 
        
        PaginatedQueryTxs.initialize(this, totalCount, count, pageNumber, pageTotal, limit, txs);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, totalCount, count, pageNumber, pageTotal, limit, txs) { 
        obj['total_count'] = totalCount;
        obj['count'] = count;
        obj['page_number'] = pageNumber;
        obj['page_total'] = pageTotal;
        obj['limit'] = limit;
        obj['txs'] = txs;
    }

    /**
     * Constructs a <code>PaginatedQueryTxs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaginatedQueryTxs} obj Optional instance to populate.
     * @return {module:model/PaginatedQueryTxs} The populated <code>PaginatedQueryTxs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginatedQueryTxs();

            if (data.hasOwnProperty('total_count')) {
                obj['total_count'] = ApiClient.convertToType(data['total_count'], 'Number');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('page_number')) {
                obj['page_number'] = ApiClient.convertToType(data['page_number'], 'Number');
            }
            if (data.hasOwnProperty('page_total')) {
                obj['page_total'] = ApiClient.convertToType(data['page_total'], 'Number');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('txs')) {
                obj['txs'] = ApiClient.convertToType(data['txs'], [TxQuery]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} total_count
 */
PaginatedQueryTxs.prototype['total_count'] = undefined;

/**
 * @member {Number} count
 */
PaginatedQueryTxs.prototype['count'] = undefined;

/**
 * @member {Number} page_number
 */
PaginatedQueryTxs.prototype['page_number'] = undefined;

/**
 * @member {Number} page_total
 */
PaginatedQueryTxs.prototype['page_total'] = undefined;

/**
 * @member {Number} limit
 */
PaginatedQueryTxs.prototype['limit'] = undefined;

/**
 * @member {Array.<module:model/TxQuery>} txs
 */
PaginatedQueryTxs.prototype['txs'] = undefined;






export default PaginatedQueryTxs;

