/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BigDecimal from './BigDecimal';
import TxQuery from './TxQuery';

/**
* The PaginatedQueryTxs model module.
* @module model/PaginatedQueryTxs
* @version 3.0
*/
export default class PaginatedQueryTxs {
    /**
    * Constructs a new <code>PaginatedQueryTxs</code>.
    * @alias module:model/PaginatedQueryTxs
    * @class
    * @param totalCount {module:model/BigDecimal} 
    * @param count {module:model/BigDecimal} 
    * @param pageNumber {module:model/BigDecimal} 
    * @param pageTotal {module:model/BigDecimal} 
    * @param limit {module:model/BigDecimal} 
    * @param txs {Array.<module:model/TxQuery>} 
    */

    constructor(totalCount, count, pageNumber, pageTotal, limit, txs) {
        
        
        this['total_count'] = totalCount;
        this['count'] = count;
        this['page_number'] = pageNumber;
        this['page_total'] = pageTotal;
        this['limit'] = limit;
        this['txs'] = txs;
        
    }

    /**
    * Constructs a <code>PaginatedQueryTxs</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaginatedQueryTxs} obj Optional instance to populate.
    * @return {module:model/PaginatedQueryTxs} The populated <code>PaginatedQueryTxs</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginatedQueryTxs();
                        
            
            if (data.hasOwnProperty('total_count')) {
                obj['total_count'] = ApiClient.convertToType(data['total_count'], BigDecimal);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], BigDecimal);
            }
            if (data.hasOwnProperty('page_number')) {
                obj['page_number'] = ApiClient.convertToType(data['page_number'], BigDecimal);
            }
            if (data.hasOwnProperty('page_total')) {
                obj['page_total'] = ApiClient.convertToType(data['page_total'], BigDecimal);
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], BigDecimal);
            }
            if (data.hasOwnProperty('txs')) {
                obj['txs'] = ApiClient.convertToType(data['txs'], [TxQuery]);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/BigDecimal} total_count
    */
    total_count = undefined;
    /**
    * @member {module:model/BigDecimal} count
    */
    count = undefined;
    /**
    * @member {module:model/BigDecimal} page_number
    */
    page_number = undefined;
    /**
    * @member {module:model/BigDecimal} page_total
    */
    page_total = undefined;
    /**
    * @member {module:model/BigDecimal} limit
    */
    limit = undefined;
    /**
    * @member {Array.<module:model/TxQuery>} txs
    */
    txs = undefined;




}
