/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SigningInfo model module.
* @module model/SigningInfo
* @version 3.0
*/
export default class SigningInfo {
    /**
    * Constructs a new <code>SigningInfo</code>.
    * @alias module:model/SigningInfo
    * @class
    * @param startHeight {String} 
    * @param indexOffset {String} 
    * @param jailedUntil {String} 
    * @param missedBlocksCounter {String} 
    */

    constructor(startHeight, indexOffset, jailedUntil, missedBlocksCounter) {
        
        
        this['start_height'] = startHeight;
        this['index_offset'] = indexOffset;
        this['jailed_until'] = jailedUntil;
        this['missed_blocks_counter'] = missedBlocksCounter;
        
    }

    /**
    * Constructs a <code>SigningInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SigningInfo} obj Optional instance to populate.
    * @return {module:model/SigningInfo} The populated <code>SigningInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SigningInfo();
                        
            
            if (data.hasOwnProperty('start_height')) {
                obj['start_height'] = ApiClient.convertToType(data['start_height'], 'String');
            }
            if (data.hasOwnProperty('index_offset')) {
                obj['index_offset'] = ApiClient.convertToType(data['index_offset'], 'String');
            }
            if (data.hasOwnProperty('jailed_until')) {
                obj['jailed_until'] = ApiClient.convertToType(data['jailed_until'], 'String');
            }
            if (data.hasOwnProperty('missed_blocks_counter')) {
                obj['missed_blocks_counter'] = ApiClient.convertToType(data['missed_blocks_counter'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} start_height
    */
    start_height = undefined;
    /**
    * @member {String} index_offset
    */
    index_offset = undefined;
    /**
    * @member {String} jailed_until
    */
    jailed_until = undefined;
    /**
    * @member {String} missed_blocks_counter
    */
    missed_blocks_counter = undefined;




}
