/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SigningInfo model module.
 * @module model/SigningInfo
 * @version 3.0
 */
class SigningInfo {
    /**
     * Constructs a new <code>SigningInfo</code>.
     * @alias module:model/SigningInfo
     * @param startHeight {String} 
     * @param indexOffset {String} 
     * @param jailedUntil {String} 
     * @param missedBlocksCounter {String} 
     */
    constructor(startHeight, indexOffset, jailedUntil, missedBlocksCounter) { 
        
        SigningInfo.initialize(this, startHeight, indexOffset, jailedUntil, missedBlocksCounter);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startHeight, indexOffset, jailedUntil, missedBlocksCounter) { 
        obj['start_height'] = startHeight;
        obj['index_offset'] = indexOffset;
        obj['jailed_until'] = jailedUntil;
        obj['missed_blocks_counter'] = missedBlocksCounter;
    }

    /**
     * Constructs a <code>SigningInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SigningInfo} obj Optional instance to populate.
     * @return {module:model/SigningInfo} The populated <code>SigningInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SigningInfo();

            if (data.hasOwnProperty('start_height')) {
                obj['start_height'] = ApiClient.convertToType(data['start_height'], 'String');
            }
            if (data.hasOwnProperty('index_offset')) {
                obj['index_offset'] = ApiClient.convertToType(data['index_offset'], 'String');
            }
            if (data.hasOwnProperty('jailed_until')) {
                obj['jailed_until'] = ApiClient.convertToType(data['jailed_until'], 'String');
            }
            if (data.hasOwnProperty('missed_blocks_counter')) {
                obj['missed_blocks_counter'] = ApiClient.convertToType(data['missed_blocks_counter'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} start_height
 */
SigningInfo.prototype['start_height'] = undefined;

/**
 * @member {String} index_offset
 */
SigningInfo.prototype['index_offset'] = undefined;

/**
 * @member {String} jailed_until
 */
SigningInfo.prototype['jailed_until'] = undefined;

/**
 * @member {String} missed_blocks_counter
 */
SigningInfo.prototype['missed_blocks_counter'] = undefined;






export default SigningInfo;

