/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StdTxCoreFee from './StdTxCoreFee';
import StdTxCoreSignatures from './StdTxCoreSignatures';

/**
 * The StdTxCore model module.
 * @module model/StdTxCore
 * @version 3.0
 */
class StdTxCore {
    /**
     * Constructs a new <code>StdTxCore</code>.
     * @alias module:model/StdTxCore
     * @param fee {module:model/StdTxCoreFee} 
     * @param memo {String} 
     * @param signatures {Array.<module:model/StdTxCoreSignatures>} 
     */
    constructor(fee, memo, signatures) { 
        
        StdTxCore.initialize(this, fee, memo, signatures);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fee, memo, signatures) { 
        obj['fee'] = fee;
        obj['memo'] = memo;
        obj['signatures'] = signatures;
    }

    /**
     * Constructs a <code>StdTxCore</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StdTxCore} obj Optional instance to populate.
     * @return {module:model/StdTxCore} The populated <code>StdTxCore</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StdTxCore();

            if (data.hasOwnProperty('msg')) {
                obj['msg'] = ApiClient.convertToType(data['msg'], [Object]);
            }
            if (data.hasOwnProperty('fee')) {
                obj['fee'] = StdTxCoreFee.constructFromObject(data['fee']);
            }
            if (data.hasOwnProperty('memo')) {
                obj['memo'] = ApiClient.convertToType(data['memo'], 'String');
            }
            if (data.hasOwnProperty('signatures')) {
                obj['signatures'] = ApiClient.convertToType(data['signatures'], [StdTxCoreSignatures]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Object>} msg
 */
StdTxCore.prototype['msg'] = undefined;

/**
 * @member {module:model/StdTxCoreFee} fee
 */
StdTxCore.prototype['fee'] = undefined;

/**
 * @member {String} memo
 */
StdTxCore.prototype['memo'] = undefined;

/**
 * @member {Array.<module:model/StdTxCoreSignatures>} signatures
 */
StdTxCore.prototype['signatures'] = undefined;






export default StdTxCore;

