/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TransferRecord from './TransferRecord';

/**
 * The Tx model module.
 * @module model/Tx
 * @version 3.0
 */
class Tx {
    /**
     * Constructs a new <code>Tx</code>.
     * @alias module:model/Tx
     */
    constructor() { 
        
        Tx.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Tx</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Tx} obj Optional instance to populate.
     * @return {module:model/Tx} The populated <code>Tx</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tx();

            if (data.hasOwnProperty('signers')) {
                obj['signers'] = ApiClient.convertToType(data['signers'], ['String']);
            }
            if (data.hasOwnProperty('transfers')) {
                obj['transfers'] = ApiClient.convertToType(data['transfers'], [TransferRecord]);
            }
            if (data.hasOwnProperty('serial_number')) {
                obj['serial_number'] = ApiClient.convertToType(data['serial_number'], 'Number');
            }
            if (data.hasOwnProperty('msg_types')) {
                obj['msg_types'] = ApiClient.convertToType(data['msg_types'], ['String']);
            }
            if (data.hasOwnProperty('tx_json')) {
                obj['tx_json'] = ApiClient.convertToType(data['tx_json'], 'String');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} signers
 */
Tx.prototype['signers'] = undefined;

/**
 * @member {Array.<module:model/TransferRecord>} transfers
 */
Tx.prototype['transfers'] = undefined;

/**
 * Tx global serial number
 * @member {Number} serial_number
 */
Tx.prototype['serial_number'] = undefined;

/**
 * @member {Array.<String>} msg_types
 */
Tx.prototype['msg_types'] = undefined;

/**
 * Raw tx json byte
 * @member {String} tx_json
 */
Tx.prototype['tx_json'] = undefined;

/**
 * @member {Number} height
 */
Tx.prototype['height'] = undefined;

/**
 * The tx hash
 * @member {String} hash
 */
Tx.prototype['hash'] = undefined;






export default Tx;

