/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Unbonding model module.
 * @module model/Unbonding
 * @version 3.0
 */
class Unbonding {
    /**
     * Constructs a new <code>Unbonding</code>.
     * @alias module:model/Unbonding
     */
    constructor() { 
        
        Unbonding.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Unbonding</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Unbonding} obj Optional instance to populate.
     * @return {module:model/Unbonding} The populated <code>Unbonding</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Unbonding();

            if (data.hasOwnProperty('delegator')) {
                obj['delegator'] = ApiClient.convertToType(data['delegator'], 'String');
            }
            if (data.hasOwnProperty('validator')) {
                obj['validator'] = ApiClient.convertToType(data['validator'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('completion_time')) {
                obj['completion_time'] = ApiClient.convertToType(data['completion_time'], 'String');
            }
            if (data.hasOwnProperty('tx_hash')) {
                obj['tx_hash'] = ApiClient.convertToType(data['tx_hash'], 'String');
            }
        }
        return obj;
    }


}

/**
 * bech32 encoded address
 * @member {String} delegator
 */
Unbonding.prototype['delegator'] = undefined;

/**
 * bech32 encoded address
 * @member {String} validator
 */
Unbonding.prototype['validator'] = undefined;

/**
 * @member {String} amount
 */
Unbonding.prototype['amount'] = undefined;

/**
 * @member {String} completion_time
 */
Unbonding.prototype['completion_time'] = undefined;

/**
 * The tx hash
 * @member {String} tx_hash
 */
Unbonding.prototype['tx_hash'] = undefined;






export default Unbonding;

