/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UnbondingEntries from './UnbondingEntries';

/**
* The UnbondingDelegationPair model module.
* @module model/UnbondingDelegationPair
* @version 3.0
*/
export default class UnbondingDelegationPair {
    /**
    * Constructs a new <code>UnbondingDelegationPair</code>.
    * @alias module:model/UnbondingDelegationPair
    * @class
    * @param delegatorAddress {String} 
    * @param validatorAddress {String} 
    * @param entries {Array.<module:model/UnbondingEntries>} 
    */

    constructor(delegatorAddress, validatorAddress, entries) {
        
        
        this['delegator_address'] = delegatorAddress;
        this['validator_address'] = validatorAddress;
        this['entries'] = entries;
        
    }

    /**
    * Constructs a <code>UnbondingDelegationPair</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UnbondingDelegationPair} obj Optional instance to populate.
    * @return {module:model/UnbondingDelegationPair} The populated <code>UnbondingDelegationPair</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UnbondingDelegationPair();
                        
            
            if (data.hasOwnProperty('delegator_address')) {
                obj['delegator_address'] = ApiClient.convertToType(data['delegator_address'], 'String');
            }
            if (data.hasOwnProperty('validator_address')) {
                obj['validator_address'] = ApiClient.convertToType(data['validator_address'], 'String');
            }
            if (data.hasOwnProperty('entries')) {
                obj['entries'] = ApiClient.convertToType(data['entries'], [UnbondingEntries]);
            }
        }
        return obj;
    }

    /**
    * @member {String} delegator_address
    */
    delegator_address = undefined;
    /**
    * @member {String} validator_address
    */
    validator_address = undefined;
    /**
    * @member {Array.<module:model/UnbondingEntries>} entries
    */
    entries = undefined;




}
