/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ValidatorDescription model module.
 * @module model/ValidatorDescription
 * @version 3.0
 */
class ValidatorDescription {
    /**
     * Constructs a new <code>ValidatorDescription</code>.
     * @alias module:model/ValidatorDescription
     * @param moniker {String} 
     * @param identity {String} 
     * @param website {String} 
     * @param details {String} 
     */
    constructor(moniker, identity, website, details) { 
        
        ValidatorDescription.initialize(this, moniker, identity, website, details);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, moniker, identity, website, details) { 
        obj['moniker'] = moniker;
        obj['identity'] = identity;
        obj['website'] = website;
        obj['details'] = details;
    }

    /**
     * Constructs a <code>ValidatorDescription</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidatorDescription} obj Optional instance to populate.
     * @return {module:model/ValidatorDescription} The populated <code>ValidatorDescription</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidatorDescription();

            if (data.hasOwnProperty('moniker')) {
                obj['moniker'] = ApiClient.convertToType(data['moniker'], 'String');
            }
            if (data.hasOwnProperty('identity')) {
                obj['identity'] = ApiClient.convertToType(data['identity'], 'String');
            }
            if (data.hasOwnProperty('website')) {
                obj['website'] = ApiClient.convertToType(data['website'], 'String');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} moniker
 */
ValidatorDescription.prototype['moniker'] = undefined;

/**
 * @member {String} identity
 */
ValidatorDescription.prototype['identity'] = undefined;

/**
 * @member {String} website
 */
ValidatorDescription.prototype['website'] = undefined;

/**
 * @member {String} details
 */
ValidatorDescription.prototype['details'] = undefined;






export default ValidatorDescription;

