/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ValidatorAddress model module.
* @module model/ValidatorAddress
* @version 3.0
*/
export default class ValidatorAddress {
    /**
    * Constructs a new <code>ValidatorAddress</code>.
    * bech32 encoded address
    * @alias module:model/ValidatorAddress
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ValidatorAddress</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ValidatorAddress} obj Optional instance to populate.
    * @return {module:model/ValidatorAddress} The populated <code>ValidatorAddress</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidatorAddress();
                        
            
        }
        return obj;
    }





}
