/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BroadcastTxCommitResult from '../model/BroadcastTxCommitResult';
import InlineObject15 from '../model/InlineObject15';
import InlineObject16 from '../model/InlineObject16';
import InlineObject17 from '../model/InlineObject17';
import InlineObject18 from '../model/InlineObject18';
import InlineObject19 from '../model/InlineObject19';
import InlineResponse20029 from '../model/InlineResponse20029';
import InlineResponse20030 from '../model/InlineResponse20030';
import InlineResponse20031 from '../model/InlineResponse20031';
import InlineResponse20032 from '../model/InlineResponse20032';
import InlineResponse20033 from '../model/InlineResponse20033';
import StdTx from '../model/StdTx';

/**
* Distribution service.
* @module api/DistributionApi
* @version 3.0
*/
export default class DistributionApi {

    /**
    * Constructs a new DistributionApi. 
    * @alias module:api/DistributionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Donate to the community pool
     * Donate some amount of cet to the community pool
     * @param {String} accAddress Account address of the user
     * @param {module:model/InlineObject19} amount 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/StdTx} and HTTP response
     */
    donateToCommunityPoolWithHttpInfo(accAddress, amount) {
      let postBody = amount;
      // verify the required parameter 'accAddress' is set
      if (accAddress === undefined || accAddress === null) {
        throw new Error("Missing the required parameter 'accAddress' when calling donateToCommunityPool");
      }
      // verify the required parameter 'amount' is set
      if (amount === undefined || amount === null) {
        throw new Error("Missing the required parameter 'amount' when calling donateToCommunityPool");
      }

      let pathParams = {
        'accAddress': accAddress
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = StdTx;
      return this.apiClient.callApi(
        '/distribution/{accAddress}/donates', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Donate to the community pool
     * Donate some amount of cet to the community pool
     * @param {String} accAddress Account address of the user
     * @param {module:model/InlineObject19} amount 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/StdTx}
     */
    donateToCommunityPool(accAddress, amount) {
      return this.donateToCommunityPoolWithHttpInfo(accAddress, amount)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get the total rewards balance from all delegations
     * Get the sum of all the rewards earned by delegations by a single delegator
     * @param {String} delegatorAddr Bech32 AccAddress of Delegator
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse20029} and HTTP response
     */
    getAllRewardsWithHttpInfo(delegatorAddr) {
      let postBody = null;
      // verify the required parameter 'delegatorAddr' is set
      if (delegatorAddr === undefined || delegatorAddr === null) {
        throw new Error("Missing the required parameter 'delegatorAddr' when calling getAllRewards");
      }

      let pathParams = {
        'delegatorAddr': delegatorAddr
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse20029;
      return this.apiClient.callApi(
        '/distribution/delegators/{delegatorAddr}/rewards', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get the total rewards balance from all delegations
     * Get the sum of all the rewards earned by delegations by a single delegator
     * @param {String} delegatorAddr Bech32 AccAddress of Delegator
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse20029}
     */
    getAllRewards(delegatorAddr) {
      return this.getAllRewardsWithHttpInfo(delegatorAddr)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Community pool parameters
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getCommunityPoolWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/distribution/community_pool', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Community pool parameters
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getCommunityPool() {
      return this.getCommunityPoolWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Validator distribution information
     * Query the distribution information of a single validator
     * @param {String} validatorAddr Bech32 OperatorAddress of validator
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse20032} and HTTP response
     */
    getDistributionInfoWithHttpInfo(validatorAddr) {
      let postBody = null;
      // verify the required parameter 'validatorAddr' is set
      if (validatorAddr === undefined || validatorAddr === null) {
        throw new Error("Missing the required parameter 'validatorAddr' when calling getDistributionInfo");
      }

      let pathParams = {
        'validatorAddr': validatorAddr
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse20032;
      return this.apiClient.callApi(
        '/distribution/validators/{validatorAddr}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Validator distribution information
     * Query the distribution information of a single validator
     * @param {String} validatorAddr Bech32 OperatorAddress of validator
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse20032}
     */
    getDistributionInfo(validatorAddr) {
      return this.getDistributionInfoWithHttpInfo(validatorAddr)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fee distribution parameters
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse20033} and HTTP response
     */
    getDistributionParamsWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse20033;
      return this.apiClient.callApi(
        '/distribution/parameters', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Fee distribution parameters
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse20033}
     */
    getDistributionParams() {
      return this.getDistributionParamsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fee distribution outstanding rewards of a single validator
     * @param {String} validatorAddr Bech32 OperatorAddress of validator
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getOutstandingRewardsWithHttpInfo(validatorAddr) {
      let postBody = null;
      // verify the required parameter 'validatorAddr' is set
      if (validatorAddr === undefined || validatorAddr === null) {
        throw new Error("Missing the required parameter 'validatorAddr' when calling getOutstandingRewards");
      }

      let pathParams = {
        'validatorAddr': validatorAddr
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/distribution/validators/{validatorAddr}/outstanding_rewards', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Fee distribution outstanding rewards of a single validator
     * @param {String} validatorAddr Bech32 OperatorAddress of validator
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getOutstandingRewards(validatorAddr) {
      return this.getOutstandingRewardsWithHttpInfo(validatorAddr)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Query a delegation reward
     * Query a single delegation reward by a delegator
     * @param {String} delegatorAddr Bech32 AccAddress of Delegator
     * @param {String} validatorAddr Bech32 OperatorAddress of validator
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse20030} and HTTP response
     */
    getRewardByValidatorWithHttpInfo(delegatorAddr, validatorAddr) {
      let postBody = null;
      // verify the required parameter 'delegatorAddr' is set
      if (delegatorAddr === undefined || delegatorAddr === null) {
        throw new Error("Missing the required parameter 'delegatorAddr' when calling getRewardByValidator");
      }
      // verify the required parameter 'validatorAddr' is set
      if (validatorAddr === undefined || validatorAddr === null) {
        throw new Error("Missing the required parameter 'validatorAddr' when calling getRewardByValidator");
      }

      let pathParams = {
        'delegatorAddr': delegatorAddr,
        'validatorAddr': validatorAddr
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse20030;
      return this.apiClient.callApi(
        '/distribution/delegators/{delegatorAddr}/rewards/{validatorAddr}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Query a delegation reward
     * Query a single delegation reward by a delegator
     * @param {String} delegatorAddr Bech32 AccAddress of Delegator
     * @param {String} validatorAddr Bech32 OperatorAddress of validator
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse20030}
     */
    getRewardByValidator(delegatorAddr, validatorAddr) {
      return this.getRewardByValidatorWithHttpInfo(delegatorAddr, validatorAddr)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Commission and self-delegation rewards of a single validator
     * Query the commission and self-delegation rewards of validator.
     * @param {String} validatorAddr Bech32 OperatorAddress of validator
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse20030} and HTTP response
     */
    getValidatorRewardsWithHttpInfo(validatorAddr) {
      let postBody = null;
      // verify the required parameter 'validatorAddr' is set
      if (validatorAddr === undefined || validatorAddr === null) {
        throw new Error("Missing the required parameter 'validatorAddr' when calling getValidatorRewards");
      }

      let pathParams = {
        'validatorAddr': validatorAddr
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse20030;
      return this.apiClient.callApi(
        '/distribution/validators/{validatorAddr}/rewards', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Commission and self-delegation rewards of a single validator
     * Query the commission and self-delegation rewards of validator.
     * @param {String} validatorAddr Bech32 OperatorAddress of validator
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse20030}
     */
    getValidatorRewards(validatorAddr) {
      return this.getValidatorRewardsWithHttpInfo(validatorAddr)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get the rewards withdrawal address
     * Get the delegations' rewards withdrawal address. This is the address in which the user will receive the reward funds
     * @param {String} delegatorAddr Bech32 AccAddress of Delegator
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse20031} and HTTP response
     */
    getWithdrawAddressWithHttpInfo(delegatorAddr) {
      let postBody = null;
      // verify the required parameter 'delegatorAddr' is set
      if (delegatorAddr === undefined || delegatorAddr === null) {
        throw new Error("Missing the required parameter 'delegatorAddr' when calling getWithdrawAddress");
      }

      let pathParams = {
        'delegatorAddr': delegatorAddr
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse20031;
      return this.apiClient.callApi(
        '/distribution/delegators/{delegatorAddr}/withdraw_address', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get the rewards withdrawal address
     * Get the delegations' rewards withdrawal address. This is the address in which the user will receive the reward funds
     * @param {String} delegatorAddr Bech32 AccAddress of Delegator
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse20031}
     */
    getWithdrawAddress(delegatorAddr) {
      return this.getWithdrawAddressWithHttpInfo(delegatorAddr)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Replace the rewards withdrawal address
     * Replace the delegations' rewards withdrawal address for a new one.
     * @param {String} delegatorAddr Bech32 AccAddress of Delegator
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject17} opts.withdrawRequestBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BroadcastTxCommitResult} and HTTP response
     */
    setWithdrawAddressWithHttpInfo(delegatorAddr, opts) {
      opts = opts || {};
      let postBody = opts['withdrawRequestBody'];
      // verify the required parameter 'delegatorAddr' is set
      if (delegatorAddr === undefined || delegatorAddr === null) {
        throw new Error("Missing the required parameter 'delegatorAddr' when calling setWithdrawAddress");
      }

      let pathParams = {
        'delegatorAddr': delegatorAddr
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = BroadcastTxCommitResult;
      return this.apiClient.callApi(
        '/distribution/delegators/{delegatorAddr}/withdraw_address', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Replace the rewards withdrawal address
     * Replace the delegations' rewards withdrawal address for a new one.
     * @param {String} delegatorAddr Bech32 AccAddress of Delegator
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject17} opts.withdrawRequestBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BroadcastTxCommitResult}
     */
    setWithdrawAddress(delegatorAddr, opts) {
      return this.setWithdrawAddressWithHttpInfo(delegatorAddr, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Withdraw all the delegator's delegation rewards
     * Withdraw all the delegator's delegation rewards
     * @param {String} delegatorAddr Bech32 AccAddress of Delegator
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject15} opts.withdrawRequestBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BroadcastTxCommitResult} and HTTP response
     */
    withdrawAllRewardsWithHttpInfo(delegatorAddr, opts) {
      opts = opts || {};
      let postBody = opts['withdrawRequestBody'];
      // verify the required parameter 'delegatorAddr' is set
      if (delegatorAddr === undefined || delegatorAddr === null) {
        throw new Error("Missing the required parameter 'delegatorAddr' when calling withdrawAllRewards");
      }

      let pathParams = {
        'delegatorAddr': delegatorAddr
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = BroadcastTxCommitResult;
      return this.apiClient.callApi(
        '/distribution/delegators/{delegatorAddr}/rewards', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Withdraw all the delegator's delegation rewards
     * Withdraw all the delegator's delegation rewards
     * @param {String} delegatorAddr Bech32 AccAddress of Delegator
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject15} opts.withdrawRequestBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BroadcastTxCommitResult}
     */
    withdrawAllRewards(delegatorAddr, opts) {
      return this.withdrawAllRewardsWithHttpInfo(delegatorAddr, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Withdraw the validator's rewards
     * Withdraw the validator's self-delegation and commissions rewards
     * @param {String} validatorAddr Bech32 OperatorAddress of validator
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject18} opts.withdrawRequestBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BroadcastTxCommitResult} and HTTP response
     */
    withdrawAllValidatorRewardsWithHttpInfo(validatorAddr, opts) {
      opts = opts || {};
      let postBody = opts['withdrawRequestBody'];
      // verify the required parameter 'validatorAddr' is set
      if (validatorAddr === undefined || validatorAddr === null) {
        throw new Error("Missing the required parameter 'validatorAddr' when calling withdrawAllValidatorRewards");
      }

      let pathParams = {
        'validatorAddr': validatorAddr
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = BroadcastTxCommitResult;
      return this.apiClient.callApi(
        '/distribution/validators/{validatorAddr}/rewards', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Withdraw the validator's rewards
     * Withdraw the validator's self-delegation and commissions rewards
     * @param {String} validatorAddr Bech32 OperatorAddress of validator
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject18} opts.withdrawRequestBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BroadcastTxCommitResult}
     */
    withdrawAllValidatorRewards(validatorAddr, opts) {
      return this.withdrawAllValidatorRewardsWithHttpInfo(validatorAddr, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Withdraw a delegation reward
     * Withdraw a delegator's delegation reward from a single validator
     * @param {String} delegatorAddr Bech32 AccAddress of Delegator
     * @param {String} validatorAddr Bech32 OperatorAddress of validator
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject16} opts.withdrawRequestBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BroadcastTxCommitResult} and HTTP response
     */
    withdrawRewardsByValidatorWithHttpInfo(delegatorAddr, validatorAddr, opts) {
      opts = opts || {};
      let postBody = opts['withdrawRequestBody'];
      // verify the required parameter 'delegatorAddr' is set
      if (delegatorAddr === undefined || delegatorAddr === null) {
        throw new Error("Missing the required parameter 'delegatorAddr' when calling withdrawRewardsByValidator");
      }
      // verify the required parameter 'validatorAddr' is set
      if (validatorAddr === undefined || validatorAddr === null) {
        throw new Error("Missing the required parameter 'validatorAddr' when calling withdrawRewardsByValidator");
      }

      let pathParams = {
        'delegatorAddr': delegatorAddr,
        'validatorAddr': validatorAddr
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = BroadcastTxCommitResult;
      return this.apiClient.callApi(
        '/distribution/delegators/{delegatorAddr}/rewards/{validatorAddr}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Withdraw a delegation reward
     * Withdraw a delegator's delegation reward from a single validator
     * @param {String} delegatorAddr Bech32 AccAddress of Delegator
     * @param {String} validatorAddr Bech32 OperatorAddress of validator
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject16} opts.withdrawRequestBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BroadcastTxCommitResult}
     */
    withdrawRewardsByValidator(delegatorAddr, validatorAddr, opts) {
      return this.withdrawRewardsByValidatorWithHttpInfo(delegatorAddr, validatorAddr, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
