/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DexApiNodejs);
  }
}(this, function(expect, DexApiNodejs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DexApiNodejs.CancelOrderInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CancelOrderInfo', function() {
    it('should create an instance of CancelOrderInfo', function() {
      // uncomment below and update the code to test CancelOrderInfo
      //var instane = new DexApiNodejs.CancelOrderInfo();
      //expect(instance).to.be.a(DexApiNodejs.CancelOrderInfo);
    });

    it('should have the property orderId (base name: "order_id")', function() {
      // uncomment below and update the code to test the property orderId
      //var instane = new DexApiNodejs.CancelOrderInfo();
      //expect(instance).to.be();
    });

    it('should have the property tradingPair (base name: "trading_pair")', function() {
      // uncomment below and update the code to test the property tradingPair
      //var instane = new DexApiNodejs.CancelOrderInfo();
      //expect(instance).to.be();
    });

    it('should have the property height (base name: "height")', function() {
      // uncomment below and update the code to test the property height
      //var instane = new DexApiNodejs.CancelOrderInfo();
      //expect(instance).to.be();
    });

    it('should have the property side (base name: "side")', function() {
      // uncomment below and update the code to test the property side
      //var instane = new DexApiNodejs.CancelOrderInfo();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instane = new DexApiNodejs.CancelOrderInfo();
      //expect(instance).to.be();
    });

    it('should have the property delReason (base name: "del_reason")', function() {
      // uncomment below and update the code to test the property delReason
      //var instane = new DexApiNodejs.CancelOrderInfo();
      //expect(instance).to.be();
    });

    it('should have the property usedCommission (base name: "used_commission")', function() {
      // uncomment below and update the code to test the property usedCommission
      //var instane = new DexApiNodejs.CancelOrderInfo();
      //expect(instance).to.be();
    });

    it('should have the property leftStock (base name: "left_stock")', function() {
      // uncomment below and update the code to test the property leftStock
      //var instane = new DexApiNodejs.CancelOrderInfo();
      //expect(instance).to.be();
    });

    it('should have the property remainAmount (base name: "remain_amount")', function() {
      // uncomment below and update the code to test the property remainAmount
      //var instane = new DexApiNodejs.CancelOrderInfo();
      //expect(instance).to.be();
    });

    it('should have the property dealStock (base name: "deal_stock")', function() {
      // uncomment below and update the code to test the property dealStock
      //var instane = new DexApiNodejs.CancelOrderInfo();
      //expect(instance).to.be();
    });

    it('should have the property dealMoney (base name: "deal_money")', function() {
      // uncomment below and update the code to test the property dealMoney
      //var instane = new DexApiNodejs.CancelOrderInfo();
      //expect(instance).to.be();
    });

    it('should have the property txHash (base name: "tx_hash")', function() {
      // uncomment below and update the code to test the property txHash
      //var instane = new DexApiNodejs.CancelOrderInfo();
      //expect(instance).to.be();
    });

  });

}));
