/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DexApiNodejs);
  }
}(this, function(expect, DexApiNodejs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DexApiNodejs.InlineResponse20014Result();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse20014Result', function() {
    it('should create an instance of InlineResponse20014Result', function() {
      // uncomment below and update the code to test InlineResponse20014Result
      //var instane = new DexApiNodejs.InlineResponse20014Result();
      //expect(instance).to.be.a(DexApiNodejs.InlineResponse20014Result);
    });

    it('should have the property maxEntries (base name: "max_entries")', function() {
      // uncomment below and update the code to test the property maxEntries
      //var instane = new DexApiNodejs.InlineResponse20014Result();
      //expect(instance).to.be();
    });

    it('should have the property unbondingTime (base name: "unbonding_time")', function() {
      // uncomment below and update the code to test the property unbondingTime
      //var instane = new DexApiNodejs.InlineResponse20014Result();
      //expect(instance).to.be();
    });

    it('should have the property maxValidators (base name: "max_validators")', function() {
      // uncomment below and update the code to test the property maxValidators
      //var instane = new DexApiNodejs.InlineResponse20014Result();
      //expect(instance).to.be();
    });

    it('should have the property bondDenom (base name: "bond_denom")', function() {
      // uncomment below and update the code to test the property bondDenom
      //var instane = new DexApiNodejs.InlineResponse20014Result();
      //expect(instance).to.be();
    });

    it('should have the property minSelfDelegation (base name: "min_self_delegation")', function() {
      // uncomment below and update the code to test the property minSelfDelegation
      //var instane = new DexApiNodejs.InlineResponse20014Result();
      //expect(instance).to.be();
    });

    it('should have the property minMandatoryCommissionRate (base name: "min_mandatory_commission_rate")', function() {
      // uncomment below and update the code to test the property minMandatoryCommissionRate
      //var instane = new DexApiNodejs.InlineResponse20014Result();
      //expect(instance).to.be();
    });

  });

}));
