/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DexApiNodejs);
  }
}(this, function(expect, DexApiNodejs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DexApiNodejs.InlineObject10();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineObject10', function() {
    it('should create an instance of InlineObject10', function() {
      // uncomment below and update the code to test InlineObject10
      //var instane = new DexApiNodejs.InlineObject10();
      //expect(instance).to.be.a(DexApiNodejs.InlineObject10);
    });

    it('should have the property baseReq (base name: "base_req")', function() {
      // uncomment below and update the code to test the property baseReq
      //var instane = new DexApiNodejs.InlineObject10();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new DexApiNodejs.InlineObject10();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new DexApiNodejs.InlineObject10();
      //expect(instance).to.be();
    });

    it('should have the property proposalType (base name: "proposal_type")', function() {
      // uncomment below and update the code to test the property proposalType
      //var instane = new DexApiNodejs.InlineObject10();
      //expect(instance).to.be();
    });

    it('should have the property proposer (base name: "proposer")', function() {
      // uncomment below and update the code to test the property proposer
      //var instane = new DexApiNodejs.InlineObject10();
      //expect(instance).to.be();
    });

    it('should have the property initialDeposit (base name: "initial_deposit")', function() {
      // uncomment below and update the code to test the property initialDeposit
      //var instane = new DexApiNodejs.InlineObject10();
      //expect(instance).to.be();
    });

  });

}));
