/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DexApiNodejs);
  }
}(this, function(expect, DexApiNodejs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DexApiNodejs.RedelegationEntry();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RedelegationEntry', function() {
    it('should create an instance of RedelegationEntry', function() {
      // uncomment below and update the code to test RedelegationEntry
      //var instane = new DexApiNodejs.RedelegationEntry();
      //expect(instance).to.be.a(DexApiNodejs.RedelegationEntry);
    });

    it('should have the property creationHeight (base name: "creation_height")', function() {
      // uncomment below and update the code to test the property creationHeight
      //var instane = new DexApiNodejs.RedelegationEntry();
      //expect(instance).to.be();
    });

    it('should have the property completionTime (base name: "completion_time")', function() {
      // uncomment below and update the code to test the property completionTime
      //var instane = new DexApiNodejs.RedelegationEntry();
      //expect(instance).to.be();
    });

    it('should have the property initialBalance (base name: "initial_balance")', function() {
      // uncomment below and update the code to test the property initialBalance
      //var instane = new DexApiNodejs.RedelegationEntry();
      //expect(instance).to.be();
    });

    it('should have the property sharesDst (base name: "shares_dst")', function() {
      // uncomment below and update the code to test the property sharesDst
      //var instane = new DexApiNodejs.RedelegationEntry();
      //expect(instance).to.be();
    });

    it('should have the property balance (base name: "balance")', function() {
      // uncomment below and update the code to test the property balance
      //var instane = new DexApiNodejs.RedelegationEntry();
      //expect(instance).to.be();
    });

  });

}));
