/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DexApiNodejs);
  }
}(this, function(expect, DexApiNodejs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DexApiNodejs.Tx();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Tx', function() {
    it('should create an instance of Tx', function() {
      // uncomment below and update the code to test Tx
      //var instane = new DexApiNodejs.Tx();
      //expect(instance).to.be.a(DexApiNodejs.Tx);
    });

    it('should have the property signers (base name: "signers")', function() {
      // uncomment below and update the code to test the property signers
      //var instane = new DexApiNodejs.Tx();
      //expect(instance).to.be();
    });

    it('should have the property transfers (base name: "transfers")', function() {
      // uncomment below and update the code to test the property transfers
      //var instane = new DexApiNodejs.Tx();
      //expect(instance).to.be();
    });

    it('should have the property serialNumber (base name: "serial_number")', function() {
      // uncomment below and update the code to test the property serialNumber
      //var instane = new DexApiNodejs.Tx();
      //expect(instance).to.be();
    });

    it('should have the property msgTypes (base name: "msg_types")', function() {
      // uncomment below and update the code to test the property msgTypes
      //var instane = new DexApiNodejs.Tx();
      //expect(instance).to.be();
    });

    it('should have the property txJson (base name: "tx_json")', function() {
      // uncomment below and update the code to test the property txJson
      //var instane = new DexApiNodejs.Tx();
      //expect(instance).to.be();
    });

    it('should have the property height (base name: "height")', function() {
      // uncomment below and update the code to test the property height
      //var instane = new DexApiNodejs.Tx();
      //expect(instance).to.be();
    });

    it('should have the property hash (base name: "hash")', function() {
      // uncomment below and update the code to test the property hash
      //var instane = new DexApiNodejs.Tx();
      //expect(instance).to.be();
    });

  });

}));
