/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DexApiNodejs);
  }
}(this, function(expect, DexApiNodejs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DexApiNodejs.Validator();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Validator', function() {
    it('should create an instance of Validator', function() {
      // uncomment below and update the code to test Validator
      //var instane = new DexApiNodejs.Validator();
      //expect(instance).to.be.a(DexApiNodejs.Validator);
    });

    it('should have the property operatorAddress (base name: "operator_address")', function() {
      // uncomment below and update the code to test the property operatorAddress
      //var instane = new DexApiNodejs.Validator();
      //expect(instance).to.be();
    });

    it('should have the property consensusPubkey (base name: "consensus_pubkey")', function() {
      // uncomment below and update the code to test the property consensusPubkey
      //var instane = new DexApiNodejs.Validator();
      //expect(instance).to.be();
    });

    it('should have the property jailed (base name: "jailed")', function() {
      // uncomment below and update the code to test the property jailed
      //var instane = new DexApiNodejs.Validator();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new DexApiNodejs.Validator();
      //expect(instance).to.be();
    });

    it('should have the property tokens (base name: "tokens")', function() {
      // uncomment below and update the code to test the property tokens
      //var instane = new DexApiNodejs.Validator();
      //expect(instance).to.be();
    });

    it('should have the property delegatorShares (base name: "delegator_shares")', function() {
      // uncomment below and update the code to test the property delegatorShares
      //var instane = new DexApiNodejs.Validator();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new DexApiNodejs.Validator();
      //expect(instance).to.be();
    });

    it('should have the property unbondingHeight (base name: "unbonding_height")', function() {
      // uncomment below and update the code to test the property unbondingHeight
      //var instane = new DexApiNodejs.Validator();
      //expect(instance).to.be();
    });

    it('should have the property unbondingTime (base name: "unbonding_time")', function() {
      // uncomment below and update the code to test the property unbondingTime
      //var instane = new DexApiNodejs.Validator();
      //expect(instance).to.be();
    });

    it('should have the property commission (base name: "commission")', function() {
      // uncomment below and update the code to test the property commission
      //var instane = new DexApiNodejs.Validator();
      //expect(instance).to.be();
    });

    it('should have the property minSelfDelegation (base name: "min_self_delegation")', function() {
      // uncomment below and update the code to test the property minSelfDelegation
      //var instane = new DexApiNodejs.Validator();
      //expect(instance).to.be();
    });

  });

}));
