/**
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Addresses from './model/Addresses';
import BancorInfo from './model/BancorInfo';
import BancorTrade from './model/BancorTrade';
import BaseMarket from './model/BaseMarket';
import BaseReq from './model/BaseReq';
import Block from './model/Block';
import BlockEvidence from './model/BlockEvidence';
import BlockHeader from './model/BlockHeader';
import BlockHeaderVersion from './model/BlockHeaderVersion';
import BlockID from './model/BlockID';
import BlockIDParts from './model/BlockIDParts';
import BlockLastCommit from './model/BlockLastCommit';
import BlockLastCommitPrecommits from './model/BlockLastCommitPrecommits';
import BlockQuery from './model/BlockQuery';
import BlockQueryBlockMeta from './model/BlockQueryBlockMeta';
import BroadcastTxCommitResult from './model/BroadcastTxCommitResult';
import BroadcastTxCommitResultAttributes from './model/BroadcastTxCommitResultAttributes';
import BroadcastTxCommitResultEvents from './model/BroadcastTxCommitResultEvents';
import BroadcastTxCommitResultLogs from './model/BroadcastTxCommitResultLogs';
import CancelOrderInfo from './model/CancelOrderInfo';
import CandleStick from './model/CandleStick';
import CheckTxResult from './model/CheckTxResult';
import Coin from './model/Coin';
import Comment from './model/Comment';
import CommentRef from './model/CommentRef';
import CreateOrderInfo from './model/CreateOrderInfo';
import Delegation from './model/Delegation';
import DelegationDelegatorReward from './model/DelegationDelegatorReward';
import DelegatorTotalRewards from './model/DelegatorTotalRewards';
import DeliverTxResult from './model/DeliverTxResult';
import Deposit from './model/Deposit';
import Donation from './model/Donation';
import FillOrderInfo from './model/FillOrderInfo';
import InlineObject from './model/InlineObject';
import InlineObject1 from './model/InlineObject1';
import InlineObject10 from './model/InlineObject10';
import InlineObject11 from './model/InlineObject11';
import InlineObject12 from './model/InlineObject12';
import InlineObject13 from './model/InlineObject13';
import InlineObject14 from './model/InlineObject14';
import InlineObject15 from './model/InlineObject15';
import InlineObject16 from './model/InlineObject16';
import InlineObject17 from './model/InlineObject17';
import InlineObject18 from './model/InlineObject18';
import InlineObject19 from './model/InlineObject19';
import InlineObject2 from './model/InlineObject2';
import InlineObject20 from './model/InlineObject20';
import InlineObject21 from './model/InlineObject21';
import InlineObject22 from './model/InlineObject22';
import InlineObject23 from './model/InlineObject23';
import InlineObject24 from './model/InlineObject24';
import InlineObject25 from './model/InlineObject25';
import InlineObject26 from './model/InlineObject26';
import InlineObject27 from './model/InlineObject27';
import InlineObject28 from './model/InlineObject28';
import InlineObject29 from './model/InlineObject29';
import InlineObject3 from './model/InlineObject3';
import InlineObject30 from './model/InlineObject30';
import InlineObject31 from './model/InlineObject31';
import InlineObject32 from './model/InlineObject32';
import InlineObject33 from './model/InlineObject33';
import InlineObject34 from './model/InlineObject34';
import InlineObject35 from './model/InlineObject35';
import InlineObject4 from './model/InlineObject4';
import InlineObject5 from './model/InlineObject5';
import InlineObject6 from './model/InlineObject6';
import InlineObject7 from './model/InlineObject7';
import InlineObject8 from './model/InlineObject8';
import InlineObject9 from './model/InlineObject9';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse20010 from './model/InlineResponse20010';
import InlineResponse20011 from './model/InlineResponse20011';
import InlineResponse20012 from './model/InlineResponse20012';
import InlineResponse20013 from './model/InlineResponse20013';
import InlineResponse20013Result from './model/InlineResponse20013Result';
import InlineResponse20014 from './model/InlineResponse20014';
import InlineResponse20014Result from './model/InlineResponse20014Result';
import InlineResponse20015 from './model/InlineResponse20015';
import InlineResponse20016 from './model/InlineResponse20016';
import InlineResponse20017 from './model/InlineResponse20017';
import InlineResponse20017Result from './model/InlineResponse20017Result';
import InlineResponse20018 from './model/InlineResponse20018';
import InlineResponse20019 from './model/InlineResponse20019';
import InlineResponse2001Result from './model/InlineResponse2001Result';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse20020 from './model/InlineResponse20020';
import InlineResponse20021 from './model/InlineResponse20021';
import InlineResponse20022 from './model/InlineResponse20022';
import InlineResponse20023 from './model/InlineResponse20023';
import InlineResponse20024 from './model/InlineResponse20024';
import InlineResponse20025 from './model/InlineResponse20025';
import InlineResponse20026 from './model/InlineResponse20026';
import InlineResponse20026Result from './model/InlineResponse20026Result';
import InlineResponse20027 from './model/InlineResponse20027';
import InlineResponse20027Result from './model/InlineResponse20027Result';
import InlineResponse20028 from './model/InlineResponse20028';
import InlineResponse20028Result from './model/InlineResponse20028Result';
import InlineResponse20029 from './model/InlineResponse20029';
import InlineResponse2002Result from './model/InlineResponse2002Result';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse20030 from './model/InlineResponse20030';
import InlineResponse20031 from './model/InlineResponse20031';
import InlineResponse20032 from './model/InlineResponse20032';
import InlineResponse20033 from './model/InlineResponse20033';
import InlineResponse20033Result from './model/InlineResponse20033Result';
import InlineResponse20034 from './model/InlineResponse20034';
import InlineResponse20034Result from './model/InlineResponse20034Result';
import InlineResponse20035 from './model/InlineResponse20035';
import InlineResponse20035Result from './model/InlineResponse20035Result';
import InlineResponse20036 from './model/InlineResponse20036';
import InlineResponse20036Result from './model/InlineResponse20036Result';
import InlineResponse20036ResultPlans from './model/InlineResponse20036ResultPlans';
import InlineResponse20037 from './model/InlineResponse20037';
import InlineResponse20037Result from './model/InlineResponse20037Result';
import InlineResponse20038 from './model/InlineResponse20038';
import InlineResponse20039 from './model/InlineResponse20039';
import InlineResponse2004 from './model/InlineResponse2004';
import InlineResponse20040 from './model/InlineResponse20040';
import InlineResponse20041 from './model/InlineResponse20041';
import InlineResponse20042 from './model/InlineResponse20042';
import InlineResponse20042Result from './model/InlineResponse20042Result';
import InlineResponse20043 from './model/InlineResponse20043';
import InlineResponse20044 from './model/InlineResponse20044';
import InlineResponse20045 from './model/InlineResponse20045';
import InlineResponse20046 from './model/InlineResponse20046';
import InlineResponse20046Result from './model/InlineResponse20046Result';
import InlineResponse20047 from './model/InlineResponse20047';
import InlineResponse20048 from './model/InlineResponse20048';
import InlineResponse20049 from './model/InlineResponse20049';
import InlineResponse2004Result from './model/InlineResponse2004Result';
import InlineResponse2005 from './model/InlineResponse2005';
import InlineResponse20050 from './model/InlineResponse20050';
import InlineResponse20050Result from './model/InlineResponse20050Result';
import InlineResponse20051 from './model/InlineResponse20051';
import InlineResponse20051Result from './model/InlineResponse20051Result';
import InlineResponse20052 from './model/InlineResponse20052';
import InlineResponse20053 from './model/InlineResponse20053';
import InlineResponse20054 from './model/InlineResponse20054';
import InlineResponse20055 from './model/InlineResponse20055';
import InlineResponse20056 from './model/InlineResponse20056';
import InlineResponse20057 from './model/InlineResponse20057';
import InlineResponse20058 from './model/InlineResponse20058';
import InlineResponse20059 from './model/InlineResponse20059';
import InlineResponse2006 from './model/InlineResponse2006';
import InlineResponse20060 from './model/InlineResponse20060';
import InlineResponse20061 from './model/InlineResponse20061';
import InlineResponse20062 from './model/InlineResponse20062';
import InlineResponse20063 from './model/InlineResponse20063';
import InlineResponse20064 from './model/InlineResponse20064';
import InlineResponse2007 from './model/InlineResponse2007';
import InlineResponse2008 from './model/InlineResponse2008';
import InlineResponse2009 from './model/InlineResponse2009';
import InlineResponse200ApplicationVersion from './model/InlineResponse200ApplicationVersion';
import InlineResponse200NodeInfo from './model/InlineResponse200NodeInfo';
import InlineResponse200NodeInfoOther from './model/InlineResponse200NodeInfoOther';
import InlineResponse200NodeInfoProtocolVersion from './model/InlineResponse200NodeInfoProtocolVersion';
import IssueToken from './model/IssueToken';
import KVPair from './model/KVPair';
import KeyOutput from './model/KeyOutput';
import Locked from './model/Locked';
import LockedCoin from './model/LockedCoin';
import MarketInfo from './model/MarketInfo';
import MarketInfoAllOf from './model/MarketInfoAllOf';
import Order from './model/Order';
import OrderInfo from './model/OrderInfo';
import OrderInfoAllOf from './model/OrderInfoAllOf';
import PaginatedQueryTxs from './model/PaginatedQueryTxs';
import ParamChange from './model/ParamChange';
import PricePoint from './model/PricePoint';
import Proposer from './model/Proposer';
import PublicKey from './model/PublicKey';
import Redelegation from './model/Redelegation';
import RedelegationEntry from './model/RedelegationEntry';
import SigningInfo from './model/SigningInfo';
import Slash from './model/Slash';
import StdTx from './model/StdTx';
import StdTxCore from './model/StdTxCore';
import StdTxCoreFee from './model/StdTxCoreFee';
import StdTxCorePubKey from './model/StdTxCorePubKey';
import StdTxCoreSignatures from './model/StdTxCoreSignatures';
import Supply from './model/Supply';
import TallyResult from './model/TallyResult';
import TendermintValidator from './model/TendermintValidator';
import TextProposal from './model/TextProposal';
import TextProposalContent from './model/TextProposalContent';
import TextProposalContentValue from './model/TextProposalContentValue';
import Tickers from './model/Tickers';
import Token from './model/Token';
import TokenValue from './model/TokenValue';
import TransferRecord from './model/TransferRecord';
import Tx from './model/Tx';
import TxQuery from './model/TxQuery';
import TxQueryResult from './model/TxQueryResult';
import Unbonding from './model/Unbonding';
import UnbondingDelegationPair from './model/UnbondingDelegationPair';
import UnbondingEntries from './model/UnbondingEntries';
import Unlock from './model/Unlock';
import UserOrder from './model/UserOrder';
import UserOrderCancelOrderInfo from './model/UserOrderCancelOrderInfo';
import UserOrderCreateOrderInfo from './model/UserOrderCreateOrderInfo';
import Validator from './model/Validator';
import ValidatorCommission from './model/ValidatorCommission';
import ValidatorCommissionCommissionRates from './model/ValidatorCommissionCommissionRates';
import ValidatorDescription from './model/ValidatorDescription';
import ValidatorDistInfo from './model/ValidatorDistInfo';
import Vote from './model/Vote';
import Whitelist from './model/Whitelist';
import AliasApi from './api/AliasApi';
import AssetApi from './api/AssetApi';
import AuthApi from './api/AuthApi';
import BancorApi from './api/BancorApi';
import BancorliteApi from './api/BancorliteApi';
import BankApi from './api/BankApi';
import CommentApi from './api/CommentApi';
import DistributionApi from './api/DistributionApi';
import ExpiryApi from './api/ExpiryApi';
import GovernanceApi from './api/GovernanceApi';
import IncentiveApi from './api/IncentiveApi';
import MarketApi from './api/MarketApi';
import MiscApi from './api/MiscApi';
import SlashApi from './api/SlashApi';
import SlashingApi from './api/SlashingApi';
import StakingApi from './api/StakingApi';
import TendermintApi from './api/TendermintApi';
import TransactionsApi from './api/TransactionsApi';
import TxApi from './api/TxApi';


/**
* A_REST_interface_for_state_queries_transaction_generation_and_broadcasting_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var DexApiNodejs = require('index'); // See note below*.
* var xxxSvc = new DexApiNodejs.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new DexApiNodejs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new DexApiNodejs.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new DexApiNodejs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 3.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Addresses model constructor.
     * @property {module:model/Addresses}
     */
    Addresses,

    /**
     * The BancorInfo model constructor.
     * @property {module:model/BancorInfo}
     */
    BancorInfo,

    /**
     * The BancorTrade model constructor.
     * @property {module:model/BancorTrade}
     */
    BancorTrade,

    /**
     * The BaseMarket model constructor.
     * @property {module:model/BaseMarket}
     */
    BaseMarket,

    /**
     * The BaseReq model constructor.
     * @property {module:model/BaseReq}
     */
    BaseReq,

    /**
     * The Block model constructor.
     * @property {module:model/Block}
     */
    Block,

    /**
     * The BlockEvidence model constructor.
     * @property {module:model/BlockEvidence}
     */
    BlockEvidence,

    /**
     * The BlockHeader model constructor.
     * @property {module:model/BlockHeader}
     */
    BlockHeader,

    /**
     * The BlockHeaderVersion model constructor.
     * @property {module:model/BlockHeaderVersion}
     */
    BlockHeaderVersion,

    /**
     * The BlockID model constructor.
     * @property {module:model/BlockID}
     */
    BlockID,

    /**
     * The BlockIDParts model constructor.
     * @property {module:model/BlockIDParts}
     */
    BlockIDParts,

    /**
     * The BlockLastCommit model constructor.
     * @property {module:model/BlockLastCommit}
     */
    BlockLastCommit,

    /**
     * The BlockLastCommitPrecommits model constructor.
     * @property {module:model/BlockLastCommitPrecommits}
     */
    BlockLastCommitPrecommits,

    /**
     * The BlockQuery model constructor.
     * @property {module:model/BlockQuery}
     */
    BlockQuery,

    /**
     * The BlockQueryBlockMeta model constructor.
     * @property {module:model/BlockQueryBlockMeta}
     */
    BlockQueryBlockMeta,

    /**
     * The BroadcastTxCommitResult model constructor.
     * @property {module:model/BroadcastTxCommitResult}
     */
    BroadcastTxCommitResult,

    /**
     * The BroadcastTxCommitResultAttributes model constructor.
     * @property {module:model/BroadcastTxCommitResultAttributes}
     */
    BroadcastTxCommitResultAttributes,

    /**
     * The BroadcastTxCommitResultEvents model constructor.
     * @property {module:model/BroadcastTxCommitResultEvents}
     */
    BroadcastTxCommitResultEvents,

    /**
     * The BroadcastTxCommitResultLogs model constructor.
     * @property {module:model/BroadcastTxCommitResultLogs}
     */
    BroadcastTxCommitResultLogs,

    /**
     * The CancelOrderInfo model constructor.
     * @property {module:model/CancelOrderInfo}
     */
    CancelOrderInfo,

    /**
     * The CandleStick model constructor.
     * @property {module:model/CandleStick}
     */
    CandleStick,

    /**
     * The CheckTxResult model constructor.
     * @property {module:model/CheckTxResult}
     */
    CheckTxResult,

    /**
     * The Coin model constructor.
     * @property {module:model/Coin}
     */
    Coin,

    /**
     * The Comment model constructor.
     * @property {module:model/Comment}
     */
    Comment,

    /**
     * The CommentRef model constructor.
     * @property {module:model/CommentRef}
     */
    CommentRef,

    /**
     * The CreateOrderInfo model constructor.
     * @property {module:model/CreateOrderInfo}
     */
    CreateOrderInfo,

    /**
     * The Delegation model constructor.
     * @property {module:model/Delegation}
     */
    Delegation,

    /**
     * The DelegationDelegatorReward model constructor.
     * @property {module:model/DelegationDelegatorReward}
     */
    DelegationDelegatorReward,

    /**
     * The DelegatorTotalRewards model constructor.
     * @property {module:model/DelegatorTotalRewards}
     */
    DelegatorTotalRewards,

    /**
     * The DeliverTxResult model constructor.
     * @property {module:model/DeliverTxResult}
     */
    DeliverTxResult,

    /**
     * The Deposit model constructor.
     * @property {module:model/Deposit}
     */
    Deposit,

    /**
     * The Donation model constructor.
     * @property {module:model/Donation}
     */
    Donation,

    /**
     * The FillOrderInfo model constructor.
     * @property {module:model/FillOrderInfo}
     */
    FillOrderInfo,

    /**
     * The InlineObject model constructor.
     * @property {module:model/InlineObject}
     */
    InlineObject,

    /**
     * The InlineObject1 model constructor.
     * @property {module:model/InlineObject1}
     */
    InlineObject1,

    /**
     * The InlineObject10 model constructor.
     * @property {module:model/InlineObject10}
     */
    InlineObject10,

    /**
     * The InlineObject11 model constructor.
     * @property {module:model/InlineObject11}
     */
    InlineObject11,

    /**
     * The InlineObject12 model constructor.
     * @property {module:model/InlineObject12}
     */
    InlineObject12,

    /**
     * The InlineObject13 model constructor.
     * @property {module:model/InlineObject13}
     */
    InlineObject13,

    /**
     * The InlineObject14 model constructor.
     * @property {module:model/InlineObject14}
     */
    InlineObject14,

    /**
     * The InlineObject15 model constructor.
     * @property {module:model/InlineObject15}
     */
    InlineObject15,

    /**
     * The InlineObject16 model constructor.
     * @property {module:model/InlineObject16}
     */
    InlineObject16,

    /**
     * The InlineObject17 model constructor.
     * @property {module:model/InlineObject17}
     */
    InlineObject17,

    /**
     * The InlineObject18 model constructor.
     * @property {module:model/InlineObject18}
     */
    InlineObject18,

    /**
     * The InlineObject19 model constructor.
     * @property {module:model/InlineObject19}
     */
    InlineObject19,

    /**
     * The InlineObject2 model constructor.
     * @property {module:model/InlineObject2}
     */
    InlineObject2,

    /**
     * The InlineObject20 model constructor.
     * @property {module:model/InlineObject20}
     */
    InlineObject20,

    /**
     * The InlineObject21 model constructor.
     * @property {module:model/InlineObject21}
     */
    InlineObject21,

    /**
     * The InlineObject22 model constructor.
     * @property {module:model/InlineObject22}
     */
    InlineObject22,

    /**
     * The InlineObject23 model constructor.
     * @property {module:model/InlineObject23}
     */
    InlineObject23,

    /**
     * The InlineObject24 model constructor.
     * @property {module:model/InlineObject24}
     */
    InlineObject24,

    /**
     * The InlineObject25 model constructor.
     * @property {module:model/InlineObject25}
     */
    InlineObject25,

    /**
     * The InlineObject26 model constructor.
     * @property {module:model/InlineObject26}
     */
    InlineObject26,

    /**
     * The InlineObject27 model constructor.
     * @property {module:model/InlineObject27}
     */
    InlineObject27,

    /**
     * The InlineObject28 model constructor.
     * @property {module:model/InlineObject28}
     */
    InlineObject28,

    /**
     * The InlineObject29 model constructor.
     * @property {module:model/InlineObject29}
     */
    InlineObject29,

    /**
     * The InlineObject3 model constructor.
     * @property {module:model/InlineObject3}
     */
    InlineObject3,

    /**
     * The InlineObject30 model constructor.
     * @property {module:model/InlineObject30}
     */
    InlineObject30,

    /**
     * The InlineObject31 model constructor.
     * @property {module:model/InlineObject31}
     */
    InlineObject31,

    /**
     * The InlineObject32 model constructor.
     * @property {module:model/InlineObject32}
     */
    InlineObject32,

    /**
     * The InlineObject33 model constructor.
     * @property {module:model/InlineObject33}
     */
    InlineObject33,

    /**
     * The InlineObject34 model constructor.
     * @property {module:model/InlineObject34}
     */
    InlineObject34,

    /**
     * The InlineObject35 model constructor.
     * @property {module:model/InlineObject35}
     */
    InlineObject35,

    /**
     * The InlineObject4 model constructor.
     * @property {module:model/InlineObject4}
     */
    InlineObject4,

    /**
     * The InlineObject5 model constructor.
     * @property {module:model/InlineObject5}
     */
    InlineObject5,

    /**
     * The InlineObject6 model constructor.
     * @property {module:model/InlineObject6}
     */
    InlineObject6,

    /**
     * The InlineObject7 model constructor.
     * @property {module:model/InlineObject7}
     */
    InlineObject7,

    /**
     * The InlineObject8 model constructor.
     * @property {module:model/InlineObject8}
     */
    InlineObject8,

    /**
     * The InlineObject9 model constructor.
     * @property {module:model/InlineObject9}
     */
    InlineObject9,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse20010 model constructor.
     * @property {module:model/InlineResponse20010}
     */
    InlineResponse20010,

    /**
     * The InlineResponse20011 model constructor.
     * @property {module:model/InlineResponse20011}
     */
    InlineResponse20011,

    /**
     * The InlineResponse20012 model constructor.
     * @property {module:model/InlineResponse20012}
     */
    InlineResponse20012,

    /**
     * The InlineResponse20013 model constructor.
     * @property {module:model/InlineResponse20013}
     */
    InlineResponse20013,

    /**
     * The InlineResponse20013Result model constructor.
     * @property {module:model/InlineResponse20013Result}
     */
    InlineResponse20013Result,

    /**
     * The InlineResponse20014 model constructor.
     * @property {module:model/InlineResponse20014}
     */
    InlineResponse20014,

    /**
     * The InlineResponse20014Result model constructor.
     * @property {module:model/InlineResponse20014Result}
     */
    InlineResponse20014Result,

    /**
     * The InlineResponse20015 model constructor.
     * @property {module:model/InlineResponse20015}
     */
    InlineResponse20015,

    /**
     * The InlineResponse20016 model constructor.
     * @property {module:model/InlineResponse20016}
     */
    InlineResponse20016,

    /**
     * The InlineResponse20017 model constructor.
     * @property {module:model/InlineResponse20017}
     */
    InlineResponse20017,

    /**
     * The InlineResponse20017Result model constructor.
     * @property {module:model/InlineResponse20017Result}
     */
    InlineResponse20017Result,

    /**
     * The InlineResponse20018 model constructor.
     * @property {module:model/InlineResponse20018}
     */
    InlineResponse20018,

    /**
     * The InlineResponse20019 model constructor.
     * @property {module:model/InlineResponse20019}
     */
    InlineResponse20019,

    /**
     * The InlineResponse2001Result model constructor.
     * @property {module:model/InlineResponse2001Result}
     */
    InlineResponse2001Result,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse20020 model constructor.
     * @property {module:model/InlineResponse20020}
     */
    InlineResponse20020,

    /**
     * The InlineResponse20021 model constructor.
     * @property {module:model/InlineResponse20021}
     */
    InlineResponse20021,

    /**
     * The InlineResponse20022 model constructor.
     * @property {module:model/InlineResponse20022}
     */
    InlineResponse20022,

    /**
     * The InlineResponse20023 model constructor.
     * @property {module:model/InlineResponse20023}
     */
    InlineResponse20023,

    /**
     * The InlineResponse20024 model constructor.
     * @property {module:model/InlineResponse20024}
     */
    InlineResponse20024,

    /**
     * The InlineResponse20025 model constructor.
     * @property {module:model/InlineResponse20025}
     */
    InlineResponse20025,

    /**
     * The InlineResponse20026 model constructor.
     * @property {module:model/InlineResponse20026}
     */
    InlineResponse20026,

    /**
     * The InlineResponse20026Result model constructor.
     * @property {module:model/InlineResponse20026Result}
     */
    InlineResponse20026Result,

    /**
     * The InlineResponse20027 model constructor.
     * @property {module:model/InlineResponse20027}
     */
    InlineResponse20027,

    /**
     * The InlineResponse20027Result model constructor.
     * @property {module:model/InlineResponse20027Result}
     */
    InlineResponse20027Result,

    /**
     * The InlineResponse20028 model constructor.
     * @property {module:model/InlineResponse20028}
     */
    InlineResponse20028,

    /**
     * The InlineResponse20028Result model constructor.
     * @property {module:model/InlineResponse20028Result}
     */
    InlineResponse20028Result,

    /**
     * The InlineResponse20029 model constructor.
     * @property {module:model/InlineResponse20029}
     */
    InlineResponse20029,

    /**
     * The InlineResponse2002Result model constructor.
     * @property {module:model/InlineResponse2002Result}
     */
    InlineResponse2002Result,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse20030 model constructor.
     * @property {module:model/InlineResponse20030}
     */
    InlineResponse20030,

    /**
     * The InlineResponse20031 model constructor.
     * @property {module:model/InlineResponse20031}
     */
    InlineResponse20031,

    /**
     * The InlineResponse20032 model constructor.
     * @property {module:model/InlineResponse20032}
     */
    InlineResponse20032,

    /**
     * The InlineResponse20033 model constructor.
     * @property {module:model/InlineResponse20033}
     */
    InlineResponse20033,

    /**
     * The InlineResponse20033Result model constructor.
     * @property {module:model/InlineResponse20033Result}
     */
    InlineResponse20033Result,

    /**
     * The InlineResponse20034 model constructor.
     * @property {module:model/InlineResponse20034}
     */
    InlineResponse20034,

    /**
     * The InlineResponse20034Result model constructor.
     * @property {module:model/InlineResponse20034Result}
     */
    InlineResponse20034Result,

    /**
     * The InlineResponse20035 model constructor.
     * @property {module:model/InlineResponse20035}
     */
    InlineResponse20035,

    /**
     * The InlineResponse20035Result model constructor.
     * @property {module:model/InlineResponse20035Result}
     */
    InlineResponse20035Result,

    /**
     * The InlineResponse20036 model constructor.
     * @property {module:model/InlineResponse20036}
     */
    InlineResponse20036,

    /**
     * The InlineResponse20036Result model constructor.
     * @property {module:model/InlineResponse20036Result}
     */
    InlineResponse20036Result,

    /**
     * The InlineResponse20036ResultPlans model constructor.
     * @property {module:model/InlineResponse20036ResultPlans}
     */
    InlineResponse20036ResultPlans,

    /**
     * The InlineResponse20037 model constructor.
     * @property {module:model/InlineResponse20037}
     */
    InlineResponse20037,

    /**
     * The InlineResponse20037Result model constructor.
     * @property {module:model/InlineResponse20037Result}
     */
    InlineResponse20037Result,

    /**
     * The InlineResponse20038 model constructor.
     * @property {module:model/InlineResponse20038}
     */
    InlineResponse20038,

    /**
     * The InlineResponse20039 model constructor.
     * @property {module:model/InlineResponse20039}
     */
    InlineResponse20039,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse20040 model constructor.
     * @property {module:model/InlineResponse20040}
     */
    InlineResponse20040,

    /**
     * The InlineResponse20041 model constructor.
     * @property {module:model/InlineResponse20041}
     */
    InlineResponse20041,

    /**
     * The InlineResponse20042 model constructor.
     * @property {module:model/InlineResponse20042}
     */
    InlineResponse20042,

    /**
     * The InlineResponse20042Result model constructor.
     * @property {module:model/InlineResponse20042Result}
     */
    InlineResponse20042Result,

    /**
     * The InlineResponse20043 model constructor.
     * @property {module:model/InlineResponse20043}
     */
    InlineResponse20043,

    /**
     * The InlineResponse20044 model constructor.
     * @property {module:model/InlineResponse20044}
     */
    InlineResponse20044,

    /**
     * The InlineResponse20045 model constructor.
     * @property {module:model/InlineResponse20045}
     */
    InlineResponse20045,

    /**
     * The InlineResponse20046 model constructor.
     * @property {module:model/InlineResponse20046}
     */
    InlineResponse20046,

    /**
     * The InlineResponse20046Result model constructor.
     * @property {module:model/InlineResponse20046Result}
     */
    InlineResponse20046Result,

    /**
     * The InlineResponse20047 model constructor.
     * @property {module:model/InlineResponse20047}
     */
    InlineResponse20047,

    /**
     * The InlineResponse20048 model constructor.
     * @property {module:model/InlineResponse20048}
     */
    InlineResponse20048,

    /**
     * The InlineResponse20049 model constructor.
     * @property {module:model/InlineResponse20049}
     */
    InlineResponse20049,

    /**
     * The InlineResponse2004Result model constructor.
     * @property {module:model/InlineResponse2004Result}
     */
    InlineResponse2004Result,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse20050 model constructor.
     * @property {module:model/InlineResponse20050}
     */
    InlineResponse20050,

    /**
     * The InlineResponse20050Result model constructor.
     * @property {module:model/InlineResponse20050Result}
     */
    InlineResponse20050Result,

    /**
     * The InlineResponse20051 model constructor.
     * @property {module:model/InlineResponse20051}
     */
    InlineResponse20051,

    /**
     * The InlineResponse20051Result model constructor.
     * @property {module:model/InlineResponse20051Result}
     */
    InlineResponse20051Result,

    /**
     * The InlineResponse20052 model constructor.
     * @property {module:model/InlineResponse20052}
     */
    InlineResponse20052,

    /**
     * The InlineResponse20053 model constructor.
     * @property {module:model/InlineResponse20053}
     */
    InlineResponse20053,

    /**
     * The InlineResponse20054 model constructor.
     * @property {module:model/InlineResponse20054}
     */
    InlineResponse20054,

    /**
     * The InlineResponse20055 model constructor.
     * @property {module:model/InlineResponse20055}
     */
    InlineResponse20055,

    /**
     * The InlineResponse20056 model constructor.
     * @property {module:model/InlineResponse20056}
     */
    InlineResponse20056,

    /**
     * The InlineResponse20057 model constructor.
     * @property {module:model/InlineResponse20057}
     */
    InlineResponse20057,

    /**
     * The InlineResponse20058 model constructor.
     * @property {module:model/InlineResponse20058}
     */
    InlineResponse20058,

    /**
     * The InlineResponse20059 model constructor.
     * @property {module:model/InlineResponse20059}
     */
    InlineResponse20059,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse20060 model constructor.
     * @property {module:model/InlineResponse20060}
     */
    InlineResponse20060,

    /**
     * The InlineResponse20061 model constructor.
     * @property {module:model/InlineResponse20061}
     */
    InlineResponse20061,

    /**
     * The InlineResponse20062 model constructor.
     * @property {module:model/InlineResponse20062}
     */
    InlineResponse20062,

    /**
     * The InlineResponse20063 model constructor.
     * @property {module:model/InlineResponse20063}
     */
    InlineResponse20063,

    /**
     * The InlineResponse20064 model constructor.
     * @property {module:model/InlineResponse20064}
     */
    InlineResponse20064,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse2009 model constructor.
     * @property {module:model/InlineResponse2009}
     */
    InlineResponse2009,

    /**
     * The InlineResponse200ApplicationVersion model constructor.
     * @property {module:model/InlineResponse200ApplicationVersion}
     */
    InlineResponse200ApplicationVersion,

    /**
     * The InlineResponse200NodeInfo model constructor.
     * @property {module:model/InlineResponse200NodeInfo}
     */
    InlineResponse200NodeInfo,

    /**
     * The InlineResponse200NodeInfoOther model constructor.
     * @property {module:model/InlineResponse200NodeInfoOther}
     */
    InlineResponse200NodeInfoOther,

    /**
     * The InlineResponse200NodeInfoProtocolVersion model constructor.
     * @property {module:model/InlineResponse200NodeInfoProtocolVersion}
     */
    InlineResponse200NodeInfoProtocolVersion,

    /**
     * The IssueToken model constructor.
     * @property {module:model/IssueToken}
     */
    IssueToken,

    /**
     * The KVPair model constructor.
     * @property {module:model/KVPair}
     */
    KVPair,

    /**
     * The KeyOutput model constructor.
     * @property {module:model/KeyOutput}
     */
    KeyOutput,

    /**
     * The Locked model constructor.
     * @property {module:model/Locked}
     */
    Locked,

    /**
     * The LockedCoin model constructor.
     * @property {module:model/LockedCoin}
     */
    LockedCoin,

    /**
     * The MarketInfo model constructor.
     * @property {module:model/MarketInfo}
     */
    MarketInfo,

    /**
     * The MarketInfoAllOf model constructor.
     * @property {module:model/MarketInfoAllOf}
     */
    MarketInfoAllOf,

    /**
     * The Order model constructor.
     * @property {module:model/Order}
     */
    Order,

    /**
     * The OrderInfo model constructor.
     * @property {module:model/OrderInfo}
     */
    OrderInfo,

    /**
     * The OrderInfoAllOf model constructor.
     * @property {module:model/OrderInfoAllOf}
     */
    OrderInfoAllOf,

    /**
     * The PaginatedQueryTxs model constructor.
     * @property {module:model/PaginatedQueryTxs}
     */
    PaginatedQueryTxs,

    /**
     * The ParamChange model constructor.
     * @property {module:model/ParamChange}
     */
    ParamChange,

    /**
     * The PricePoint model constructor.
     * @property {module:model/PricePoint}
     */
    PricePoint,

    /**
     * The Proposer model constructor.
     * @property {module:model/Proposer}
     */
    Proposer,

    /**
     * The PublicKey model constructor.
     * @property {module:model/PublicKey}
     */
    PublicKey,

    /**
     * The Redelegation model constructor.
     * @property {module:model/Redelegation}
     */
    Redelegation,

    /**
     * The RedelegationEntry model constructor.
     * @property {module:model/RedelegationEntry}
     */
    RedelegationEntry,

    /**
     * The SigningInfo model constructor.
     * @property {module:model/SigningInfo}
     */
    SigningInfo,

    /**
     * The Slash model constructor.
     * @property {module:model/Slash}
     */
    Slash,

    /**
     * The StdTx model constructor.
     * @property {module:model/StdTx}
     */
    StdTx,

    /**
     * The StdTxCore model constructor.
     * @property {module:model/StdTxCore}
     */
    StdTxCore,

    /**
     * The StdTxCoreFee model constructor.
     * @property {module:model/StdTxCoreFee}
     */
    StdTxCoreFee,

    /**
     * The StdTxCorePubKey model constructor.
     * @property {module:model/StdTxCorePubKey}
     */
    StdTxCorePubKey,

    /**
     * The StdTxCoreSignatures model constructor.
     * @property {module:model/StdTxCoreSignatures}
     */
    StdTxCoreSignatures,

    /**
     * The Supply model constructor.
     * @property {module:model/Supply}
     */
    Supply,

    /**
     * The TallyResult model constructor.
     * @property {module:model/TallyResult}
     */
    TallyResult,

    /**
     * The TendermintValidator model constructor.
     * @property {module:model/TendermintValidator}
     */
    TendermintValidator,

    /**
     * The TextProposal model constructor.
     * @property {module:model/TextProposal}
     */
    TextProposal,

    /**
     * The TextProposalContent model constructor.
     * @property {module:model/TextProposalContent}
     */
    TextProposalContent,

    /**
     * The TextProposalContentValue model constructor.
     * @property {module:model/TextProposalContentValue}
     */
    TextProposalContentValue,

    /**
     * The Tickers model constructor.
     * @property {module:model/Tickers}
     */
    Tickers,

    /**
     * The Token model constructor.
     * @property {module:model/Token}
     */
    Token,

    /**
     * The TokenValue model constructor.
     * @property {module:model/TokenValue}
     */
    TokenValue,

    /**
     * The TransferRecord model constructor.
     * @property {module:model/TransferRecord}
     */
    TransferRecord,

    /**
     * The Tx model constructor.
     * @property {module:model/Tx}
     */
    Tx,

    /**
     * The TxQuery model constructor.
     * @property {module:model/TxQuery}
     */
    TxQuery,

    /**
     * The TxQueryResult model constructor.
     * @property {module:model/TxQueryResult}
     */
    TxQueryResult,

    /**
     * The Unbonding model constructor.
     * @property {module:model/Unbonding}
     */
    Unbonding,

    /**
     * The UnbondingDelegationPair model constructor.
     * @property {module:model/UnbondingDelegationPair}
     */
    UnbondingDelegationPair,

    /**
     * The UnbondingEntries model constructor.
     * @property {module:model/UnbondingEntries}
     */
    UnbondingEntries,

    /**
     * The Unlock model constructor.
     * @property {module:model/Unlock}
     */
    Unlock,

    /**
     * The UserOrder model constructor.
     * @property {module:model/UserOrder}
     */
    UserOrder,

    /**
     * The UserOrderCancelOrderInfo model constructor.
     * @property {module:model/UserOrderCancelOrderInfo}
     */
    UserOrderCancelOrderInfo,

    /**
     * The UserOrderCreateOrderInfo model constructor.
     * @property {module:model/UserOrderCreateOrderInfo}
     */
    UserOrderCreateOrderInfo,

    /**
     * The Validator model constructor.
     * @property {module:model/Validator}
     */
    Validator,

    /**
     * The ValidatorCommission model constructor.
     * @property {module:model/ValidatorCommission}
     */
    ValidatorCommission,

    /**
     * The ValidatorCommissionCommissionRates model constructor.
     * @property {module:model/ValidatorCommissionCommissionRates}
     */
    ValidatorCommissionCommissionRates,

    /**
     * The ValidatorDescription model constructor.
     * @property {module:model/ValidatorDescription}
     */
    ValidatorDescription,

    /**
     * The ValidatorDistInfo model constructor.
     * @property {module:model/ValidatorDistInfo}
     */
    ValidatorDistInfo,

    /**
     * The Vote model constructor.
     * @property {module:model/Vote}
     */
    Vote,

    /**
     * The Whitelist model constructor.
     * @property {module:model/Whitelist}
     */
    Whitelist,

    /**
    * The AliasApi service constructor.
    * @property {module:api/AliasApi}
    */
    AliasApi,

    /**
    * The AssetApi service constructor.
    * @property {module:api/AssetApi}
    */
    AssetApi,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The BancorApi service constructor.
    * @property {module:api/BancorApi}
    */
    BancorApi,

    /**
    * The BancorliteApi service constructor.
    * @property {module:api/BancorliteApi}
    */
    BancorliteApi,

    /**
    * The BankApi service constructor.
    * @property {module:api/BankApi}
    */
    BankApi,

    /**
    * The CommentApi service constructor.
    * @property {module:api/CommentApi}
    */
    CommentApi,

    /**
    * The DistributionApi service constructor.
    * @property {module:api/DistributionApi}
    */
    DistributionApi,

    /**
    * The ExpiryApi service constructor.
    * @property {module:api/ExpiryApi}
    */
    ExpiryApi,

    /**
    * The GovernanceApi service constructor.
    * @property {module:api/GovernanceApi}
    */
    GovernanceApi,

    /**
    * The IncentiveApi service constructor.
    * @property {module:api/IncentiveApi}
    */
    IncentiveApi,

    /**
    * The MarketApi service constructor.
    * @property {module:api/MarketApi}
    */
    MarketApi,

    /**
    * The MiscApi service constructor.
    * @property {module:api/MiscApi}
    */
    MiscApi,

    /**
    * The SlashApi service constructor.
    * @property {module:api/SlashApi}
    */
    SlashApi,

    /**
    * The SlashingApi service constructor.
    * @property {module:api/SlashingApi}
    */
    SlashingApi,

    /**
    * The StakingApi service constructor.
    * @property {module:api/StakingApi}
    */
    StakingApi,

    /**
    * The TendermintApi service constructor.
    * @property {module:api/TendermintApi}
    */
    TendermintApi,

    /**
    * The TransactionsApi service constructor.
    * @property {module:api/TransactionsApi}
    */
    TransactionsApi,

    /**
    * The TxApi service constructor.
    * @property {module:api/TxApi}
    */
    TxApi
};
